// DO NOT EDIT — regenerate via: ./gradlew :codegen:run

package io.github.glandais.engine.path

/** Bound accessor for a single [PointField], usable from KMP-safe generic code. */
internal data class PointFieldAccessor(
    val field: PointField,
    val getter: (GeneratedPath, Int) -> Double,
    val setter: (GeneratedPath, Int, Double) -> Unit,
)

internal val POINT_FIELD_ACCESSORS: List<PointFieldAccessor> =
    listOf(
        PointFieldAccessor(
            PointField.LATITUDE,
            GeneratedPath::latitude,
            GeneratedPath::setLatitude,
        ),
        PointFieldAccessor(
            PointField.LONGITUDE,
            GeneratedPath::longitude,
            GeneratedPath::setLongitude,
        ),
        PointFieldAccessor(
            PointField.DISTANCE,
            GeneratedPath::distance,
            GeneratedPath::setDistance,
        ),
        PointFieldAccessor(
            PointField.DX,
            GeneratedPath::dx,
            GeneratedPath::setDx,
        ),
        PointFieldAccessor(
            PointField.TIME,
            GeneratedPath::time,
            GeneratedPath::setTime,
        ),
        PointFieldAccessor(
            PointField.ELAPSED,
            GeneratedPath::elapsed,
            GeneratedPath::setElapsed,
        ),
        PointFieldAccessor(
            PointField.DT,
            GeneratedPath::dt,
            GeneratedPath::setDt,
        ),
        PointFieldAccessor(
            PointField.BEARING,
            GeneratedPath::bearing,
            GeneratedPath::setBearing,
        ),
        PointFieldAccessor(
            PointField.ELEVATION,
            GeneratedPath::elevation,
            GeneratedPath::setElevation,
        ),
        PointFieldAccessor(
            PointField.GRADE,
            GeneratedPath::grade,
            GeneratedPath::setGrade,
        ),
        PointFieldAccessor(
            PointField.RADIUS,
            GeneratedPath::radius,
            GeneratedPath::setRadius,
        ),
        PointFieldAccessor(
            PointField.AERO_COEF,
            GeneratedPath::aeroCoef,
            GeneratedPath::setAeroCoef,
        ),
        PointFieldAccessor(
            PointField.WIND_BEARING,
            GeneratedPath::windBearing,
            GeneratedPath::setWindBearing,
        ),
        PointFieldAccessor(
            PointField.WIND_ALPHA,
            GeneratedPath::windAlpha,
            GeneratedPath::setWindAlpha,
        ),
        PointFieldAccessor(
            PointField.P_AERO,
            GeneratedPath::pAero,
            GeneratedPath::setPAero,
        ),
        PointFieldAccessor(
            PointField.P_GRAVITY,
            GeneratedPath::pGravity,
            GeneratedPath::setPGravity,
        ),
        PointFieldAccessor(
            PointField.P_ROLLING_RESISTANCE,
            GeneratedPath::pRollingResistance,
            GeneratedPath::setPRollingResistance,
        ),
        PointFieldAccessor(
            PointField.P_WHEEL_BEARINGS,
            GeneratedPath::pWheelBearings,
            GeneratedPath::setPWheelBearings,
        ),
        PointFieldAccessor(
            PointField.P_INPUT_POWER,
            GeneratedPath::pInputPower,
            GeneratedPath::setPInputPower,
        ),
        PointFieldAccessor(
            PointField.P_CYCLIST_PROVIDED_OPTIMAL_POWER,
            GeneratedPath::pCyclistProvidedOptimalPower,
            GeneratedPath::setPCyclistProvidedOptimalPower,
        ),
        PointFieldAccessor(
            PointField.P_CYCLIST_PROVIDED_OPTIMAL_POWER_HARMONICS,
            GeneratedPath::pCyclistProvidedOptimalPowerWithHarmonics,
            GeneratedPath::setPCyclistProvidedOptimalPowerWithHarmonics,
        ),
        PointFieldAccessor(
            PointField.P_CYCLIST_PROVIDED_POWER_NEEDED,
            GeneratedPath::pCyclistPowerNeeded,
            GeneratedPath::setPCyclistPowerNeeded,
        ),
        PointFieldAccessor(
            PointField.P_CYCLIST_PROVIDED_MUSCULAR,
            GeneratedPath::pCyclistProvidedMuscular,
            GeneratedPath::setPCyclistProvidedMuscular,
        ),
        PointFieldAccessor(
            PointField.P_CYCLIST_PROVIDED_WHEEL,
            GeneratedPath::pCyclistProvidedWheel,
            GeneratedPath::setPCyclistProvidedWheel,
        ),
        PointFieldAccessor(
            PointField.P_COMPUTED_TOTAL_POWER,
            GeneratedPath::pComputedTotalPower,
            GeneratedPath::setPComputedTotalPower,
        ),
        PointFieldAccessor(
            PointField.P_COMPUTED_WHEEL_POWER,
            GeneratedPath::pComputedWheelPower,
            GeneratedPath::setPComputedWheelPower,
        ),
        PointFieldAccessor(
            PointField.POWER,
            GeneratedPath::pComputedPower,
            GeneratedPath::setPComputedPower,
        ),
        PointFieldAccessor(
            PointField.SPEED,
            GeneratedPath::speed,
            GeneratedPath::setSpeed,
        ),
        PointFieldAccessor(
            PointField.SPEED_MAX,
            GeneratedPath::speedMax,
            GeneratedPath::setSpeedMax,
        ),
        PointFieldAccessor(
            PointField.SPEED_MAX_INCLINE,
            GeneratedPath::speedMaxIncline,
            GeneratedPath::setSpeedMaxIncline,
        ),
        PointFieldAccessor(
            PointField.VIRT_SPEED_CURRENT,
            GeneratedPath::virtSpeedCurrent,
            GeneratedPath::setVirtSpeedCurrent,
        ),
        PointFieldAccessor(
            PointField.TEMPERATURE,
            GeneratedPath::temperature,
            GeneratedPath::setTemperature,
        ),
        PointFieldAccessor(
            PointField.WIND_SPEED,
            GeneratedPath::windSpeed,
            GeneratedPath::setWindSpeed,
        ),
        PointFieldAccessor(
            PointField.WIND_DIRECTION,
            GeneratedPath::windDirection,
            GeneratedPath::setWindDirection,
        ),
        PointFieldAccessor(
            PointField.HEART_RATE,
            GeneratedPath::heartRate,
            GeneratedPath::setHeartRate,
        ),
        PointFieldAccessor(
            PointField.CADENCE,
            GeneratedPath::cadence,
            GeneratedPath::setCadence,
        ),
        PointFieldAccessor(
            PointField.W_PRIME_BALANCE,
            GeneratedPath::wPrimeBalance,
            GeneratedPath::setWPrimeBalance,
        ),
    )
