package io.github.glandais.codegen.ts

import java.io.File

/**
 * Renders the TypeScript surface of one Kotlin/JS façade: `index.d.ts`, `index.mjs`, `index.cjs`.
 *
 * Why this exists rather than the compiler's `.d.ts`: Kotlin/JS emits **no body** for an
 * `external interface`, so the shipped `vcyclist-engine.d.ts` names `EnhanceOptionsDto`,
 * `PointDto` and sixteen more without ever declaring them, and `tsc` rejects the package outside
 * `skipLibCheck`. It also writes `any` for `Path`, and wraps everything in a
 * `declare namespace io.github.glandais.engine` no `import { … }` can reach.
 *
 * `external interface` is *forced* for every input DTO — an `@JsExport`ed Kotlin interface carries
 * a `__doNotUseOrImplementIt` brand no object literal satisfies, so `{ massKg: 75 }` would stop
 * compiling. The Kotlin declaration therefore stays hand-written and stays the source of truth ;
 * generation runs the other way, Kotlin → `.d.ts`. This is the opposite direction from the emitter
 * `docs/tasks/surface-alignment.md` §S10 rejected, and for the opposite reason: these declarations
 * do not exist in any published artifact, so there is nothing to reproduce.
 */
object TsFacade {
    /** One npm package's worth of façade. */
    data class Module(
        val name: String,
        val facade: File,
        val bundle: String,
        val outputDirectory: File,
        val handles: Set<String>,
        /** Pinned so a broken regex fails loudly instead of emitting a plausible, empty surface. */
        val expectedDtoCount: Int,
        val expectedFunctionCount: Int,
    )

    data class Rendered(
        val declarations: String,
        val esModule: String,
        val commonJs: String,
    )

    private const val WARNING = "// GENERATED by `./gradlew :codegen:generateTsFacade` — do not edit."

    fun modules(root: File) =
        listOf(
            Module(
                name = "engine",
                facade = File(root, "engine/src/jsMain/kotlin/io/github/glandais/engine/EngineJsApi.kt"),
                bundle = "vcyclist-engine.js",
                outputDirectory = File(root, "engine/src/jsMain/typescript"),
                handles = setOf("Path"),
                expectedDtoCount = 12,
                expectedFunctionCount = 34,
            ),
            Module(
                name = "elevation",
                facade = File(root, "elevation/src/jsMain/kotlin/io/github/glandais/elevation/ElevationJsApi.kt"),
                bundle = "vcyclist-elevation.js",
                outputDirectory = File(root, "elevation/src/jsMain/typescript"),
                handles = setOf("ElevationProvider"),
                expectedDtoCount = 6,
                expectedFunctionCount = 3,
            ),
        )

    fun enumCatalog(root: File) =
        EnumCatalog(
            listOf(
                File(root, "engine/src/commonMain/kotlin"),
                File(root, "gpx/src/commonMain/kotlin"),
                File(root, "elevation/src/commonMain/kotlin"),
            ),
        )

    /** Pure, so the staleness test can call it without touching the filesystem. */
    fun render(
        module: Module,
        enums: EnumCatalog,
    ): Rendered {
        val source = module.facade.readText()
        val types = TypeMapper(enums, module.handles)
        val dtos = KotlinFacadeParser.dtos(source, types)
        types.known = dtos.map { it.name }.toSet()
        val functions = KotlinFacadeParser.functions(source, types)

        require(dtos.size == module.expectedDtoCount) {
            "${module.name}: found ${dtos.size} external interfaces, expected ${module.expectedDtoCount}. " +
                "Bump expectedDtoCount in the same commit that adds or removes one — the pin is what " +
                "stops a broken regex from shipping an empty surface that still compiles."
        }
        require(functions.size == module.expectedFunctionCount) {
            "${module.name}: found ${functions.size} @JsExport functions, expected ${module.expectedFunctionCount}. " +
                "Bump expectedFunctionCount in the same commit."
        }

        val defaults = OptionDefaults.forFunctions(functions.map { it.name }.toSet())

        return Rendered(
            declarations = declarations(module, dtos, functions, types.unions, defaults),
            esModule = esModule(module, functions, defaults),
            commonJs = commonJs(module, functions, defaults),
        )
    }

    private fun declarations(
        module: Module,
        dtos: List<KotlinFacadeParser.Dto>,
        functions: List<KotlinFacadeParser.Function>,
        unions: Map<String, TypeMapper.Union>,
        defaults: List<OptionDefaults.Group>,
    ): String =
        buildString {
            appendLine(WARNING)
            appendLine("// Mirrors ${module.facade.path.substringAfter("src/").let { "src/$it" }}.")
            appendLine()
            for (handle in module.handles.sorted()) {
                appendLine(
                    """
                    /**
                     * An opaque Kotlin/JS `$handle` instance. It is a real JS object, but it is not
                     * `@JsExport`ed and has no TypeScript surface — reach into it through the
                     * accessor functions below, never by property.
                     *
                     * Branded rather than `object` or `any` so two handle kinds cannot be swapped,
                     * and so a typo dereferencing one is a compile error.
                     */
                    """.trimIndent(),
                )
                appendLine("declare const ${handle}Brand: unique symbol;")
                appendLine("export type $handle = { readonly [${handle}Brand]: '$handle' };")
                appendLine()
            }
            for ((alias, union) in unions) {
                appendLine(
                    "/** The spellings every door parses, derived from the `${union.enum}` catalogue in `commonMain`. */",
                )
                appendLine("export type $alias =")
                union.values.forEachIndexed { index, value ->
                    val tail = if (index == union.values.lastIndex) ";" else ""
                    appendLine("    | '$value'$tail")
                }
                appendLine()
            }
            for (dto in dtos) {
                dto.doc?.let { appendLine(tsDoc(it, 0)) }
                appendLine("export interface ${dto.name} {")
                for (property in dto.properties) {
                    property.doc?.let { appendLine(tsDoc(it, 4)) }
                    val optional = if (property.optional) "?" else ""
                    appendLine("    readonly ${property.name}$optional: ${property.type.rendered};")
                }
                appendLine("}")
                appendLine()
            }
            for (function in functions) {
                function.doc?.let { appendLine(tsDoc(it, 0)) }
                appendLine("export declare function ${function.name}(${parameters(function)}): ${function.returnType.rendered};")
                appendLine()
            }
            for (group in defaults) {
                appendLine(defaultsDoc(group))
                appendLine("export declare const ${group.constant}: {")
                for (entry in group.entries) {
                    appendLine(
                        "    readonly ${entry.wireName}: ${OptionDefaults.type(entry.value, "${group.constant}.${entry.wireName}")};",
                    )
                }
                appendLine("};")
                appendLine()
            }
        }.trimEnd() + "\n"

    /**
     * TypeScript forbids a required parameter after an optional one, so a Kotlin default only
     * becomes `?` when every parameter after it also has one.
     */
    private fun parameters(function: KotlinFacadeParser.Function): String {
        val optionalFrom =
            function.parameters
                .indexOfFirst { parameter ->
                    parameter.hasDefault &&
                        function.parameters
                            .drop(function.parameters.indexOf(parameter))
                            .all { it.hasDefault }
                }
        return function.parameters
            .mapIndexed { index, parameter ->
                val optional = if (optionalFrom >= 0 && index >= optionalFrom) "?" else ""
                "${parameter.name}$optional: ${parameter.type.rendered}"
            }.joinToString(", ")
    }

    private fun esModule(
        module: Module,
        functions: List<KotlinFacadeParser.Function>,
        defaults: List<OptionDefaults.Group>,
    ): String =
        buildString {
            appendLine(WARNING)
            appendLine("//")
            appendLine("// Kotlin/JS emits a UMD bundle that preserves the package namespace, so the module has")
            appendLine("// exactly one top-level export, `io`. This unwraps it once so consumers can write")
            appendLine("// `import { enhance } from '@glandais/vcyclist-${module.name}'`.")
            appendLine("import * as bundle from './${module.bundle}';")
            appendLine()
            appendLine("// `.js` in a package without \"type\": \"module\" is CommonJS, so an ESM `import *` yields")
            appendLine("// `{ default, 'module.exports' }` and the namespace hangs off `default`. Reading `bundle.io`")
            appendLine("// directly finds undefined, and every export below silently becomes undefined with it.")
            appendLine("const root = bundle.default ?? bundle;")
            appendLine("const ns = ${namespaceExpression(module)};")
            appendLine()
            for (function in functions) {
                appendLine("export const ${function.name} = ns.${function.name};")
            }
            for (group in defaults) {
                appendLine()
                appendLine("export const ${group.constant} = Object.freeze({")
                for (entry in group.entries) {
                    appendLine("    ${entry.wireName}: ${OptionDefaults.literal(entry.value, "${group.constant}.${entry.wireName}")},")
                }
                appendLine("});")
            }
        }

    private fun commonJs(
        module: Module,
        functions: List<KotlinFacadeParser.Function>,
        defaults: List<OptionDefaults.Group>,
    ): String =
        buildString {
            appendLine(WARNING)
            appendLine("//")
            appendLine("// The CommonJS half of the same unwrapping. Both spellings ship because the bundle is UMD")
            appendLine("// and Node resolves a bare `.js` as CommonJS — an ESM-only wrapper breaks `require()`.")
            appendLine("const root = require('./${module.bundle}');")
            appendLine()
            appendLine("const ns = ${namespaceExpression(module)};")
            appendLine()
            for (group in defaults) {
                appendLine("const ${group.constant} = Object.freeze({")
                for (entry in group.entries) {
                    appendLine("    ${entry.wireName}: ${OptionDefaults.literal(entry.value, "${group.constant}.${entry.wireName}")},")
                }
                appendLine("});")
                appendLine()
            }
            appendLine("module.exports = {")
            for (function in functions) {
                appendLine("    ${function.name}: ns.${function.name},")
            }
            for (group in defaults) {
                appendLine("    ${group.constant},")
            }
            appendLine("};")
        }

    private fun namespaceExpression(module: Module) = "root.io?.github?.glandais?.${module.name} ?? root"

    /**
     * Why a defaults constant exists at all, said once per constant rather than in a guide nobody
     * reading the `.d.ts` will open.
     */
    private fun defaultsDoc(group: OptionDefaults.Group) =
        tsDoc(
            """
            The engine's own defaults for [${group.jsFunction}], read off `${group.optionsClass}`.

            `${group.jsFunction}` takes its options **positionally**, so changing the last one means
            naming all the others and there is no field to omit. These are those values, generated
            from the same catalogue the CLI and WASI doors resolve their defaults through — never
            transcribed. Spread it and override what you need.
            """.trimIndent(),
            0,
        )

    /** KDoc → TSDoc. `[Foo]` becomes `` `Foo` ``, since TypeScript has no such link syntax. */
    private fun tsDoc(
        doc: String,
        indent: Int,
    ): String {
        val pad = " ".repeat(indent)
        val body =
            doc
                .replace("*/", "*​/")
                .replace(Regex("""\[([A-Za-z0-9_.]+)]""")) { "`${it.groupValues[1].substringAfterLast('.')}`" }
        return buildString {
            appendLine("$pad/**")
            body.lines().forEach { appendLine("$pad *${if (it.isBlank()) "" else " $it"}") }
            append("$pad */")
        }
    }
}
