@file:OptIn(UnsafeWasmMemoryApi::class, ComponentModelInternalApi::class)

package spike

import io.github.glandais.engine.gpx.GpxParser
import io.github.glandais.engine.gpx.firstTrackAsPath
import io.github.glandais.engine.path.Path
import kotlin.wasm.WasmExport
import kotlin.wasm.WasmImport
import kotlin.wasm.unsafe.ComponentModelInternalApi
import kotlin.wasm.unsafe.Pointer
import kotlin.wasm.unsafe.UnsafeWasmMemoryApi
import kotlin.wasm.unsafe.componentModelRealloc

/*
 * Throwaway guest for the w13 spike. **Not production, not built by the vcyclist Gradle build**
 * — its world is `../../spike.wit`, its verdict `docs/archive/plans/wasm-wasi-component-model.md`.
 *
 * Exports named as the Canonical ABI wants them, over the real engine. The one that matters is
 * `parse-gpx: func(gpx: string) -> s32`: it takes the string **directly out of linear memory**,
 * where the host put it through `cabi_realloc`, instead of asking for it back through
 * `vcyclist.read_input` — that is ABI v1 §4 replaced by the Canonical ABI.
 *
 * The rest are probes, and each one measured something the verdict quotes:
 *
 * | Export | What it established |
 * |---|---|
 * | `str-len` | an inbound `string` crosses intact (23 694 characters of `stelvio.gpx`) |
 * | `probe-scoped` | **the wall**: no scoped allocation is possible while the caller's memory lives |
 * | `parse-gpx-freeing` | the workaround, and that it is repeatable |
 * | `last-error` | an outbound `string`, hand-written return area included |
 * | `random-sum` | a component-model *import* is callable from Kotlin |
 * | `http-get-status` | `wasi:http` really fetches — HTTP 200 from the DEM server |
 * | `http-debug` | how the return-area offsets were found: by probing, not by reading a spec |
 *
 * Nothing here is idiomatic and nothing here should be copied into production. Every line of it
 * is what `wit-bindgen` writes for other languages.
 */
private val paths = HashMap<Int, Path>()
private var next = 1

/**
 * The allocator the Canonical ABI requires of any component that receives a `string` or a `list`.
 * `componentModelRealloc` is `@ComponentModelInternalApi` — "should not be used outside of code
 * generated by the compiler and toolchain" — so this line is exactly the decision n°2 of
 * `PLAN-WASM-WASI.md` being reopened, and the verdict has to say so.
 */
@WasmExport("cabi_realloc")
fun cabiRealloc(
    oldPtr: Int,
    oldSize: Int,
    align: Int,
    newSize: Int,
): Int {
    // Kotlin 2.4.20-Beta2's signature is `componentModelRealloc(originalPtr, originalSize,
    // newSize)`: **no alignment parameter**. The Canonical ABI passes one, and this wrapper has
    // to drop it on the floor. It happens to work here (the allocator aligns to 8, which covers
    // string, list<u8> and list<f64>) but nothing in the stdlib promises it — one more reason the
    // verdict calls this API internal rather than adoptable.
    check(align in 1..8) { "unsupported alignment $align" }
    return componentModelRealloc(oldPtr, oldSize, newSize)
}

@WasmExport("abi-version")
fun abiVersion(): Int = 1

@WasmExport("parse-gpx")
fun parseGpx(
    ptr: Int,
    len: Int,
): Int {
    val bytes = ByteArray(len)
    val base = Pointer(ptr.toUInt())
    for (i in 0 until len) bytes[i] = (base + i).loadByte()
    val path = GpxParser.parse(bytes.decodeToString()).firstTrackAsPath()
    val handle = next++
    paths[handle] = path
    return handle
}

@WasmExport("total-distance")
fun totalDistance(handle: Int): Double = paths[handle]?.totalDistance ?: -1.0

@WasmExport("path-size")
fun pathSize(handle: Int): Int = paths[handle]?.size ?: -1

/** Debug: does the Canonical ABI string transfer itself work, before any engine code runs? */
@WasmExport("str-len")
fun strLen(
    ptr: Int,
    len: Int,
): Int {
    val bytes = ByteArray(len)
    val base = Pointer(ptr.toUInt())
    for (i in 0 until len) bytes[i] = (base + i).loadByte()
    return bytes.decodeToString().length
}

/** Debug: the parse, with the failure turned into a returned code instead of an exception. */
@WasmExport("try-parse")
fun tryParse(
    ptr: Int,
    len: Int,
): Int {
    val bytes = ByteArray(len)
    val base = Pointer(ptr.toUInt())
    for (i in 0 until len) bytes[i] = (base + i).loadByte()
    return try {
        val path = GpxParser.parse(bytes.decodeToString()).firstTrackAsPath()
        val handle = next++
        paths[handle] = path
        handle
    } catch (e: Throwable) {
        lastError = e.toString()
        -1
    }
}

private var lastError = ""

@WasmExport("last-error-len")
fun lastErrorLen(): Int = lastError.encodeToByteArray().size

/**
 * An **outbound** `string`, the Canonical ABI way: a function whose result needs more than one
 * core value returns a **pointer to a return area** the guest allocated itself, into which it
 * writes `(ptr, len)`; the bytes live in memory allocated with `cabi_realloc` and the caller
 * releases both through `cabi_post_return`.
 *
 * The first attempt used the older "caller passes the return area" shape, `(param i32) -> ()`,
 * and `wasm-tools component new` refused it with `expected [] -> [I32] but found [I32] -> []` —
 * the kind of detail that is generated code's business, not a human's.
 *
 * `write_output` and its copy-during-the-call rule disappear; the ~15 lines below are what
 * replaces them, and in a real component they would be compiler-generated rather than hand-written.
 */
@WasmExport("last-error")
fun lastErrorOut(): Int {
    val bytes = lastError.encodeToByteArray()
    val ptr = componentModelRealloc(0, 0, bytes.size)
    for (i in bytes.indices) (Pointer(ptr.toUInt()) + i).storeByte(bytes[i])
    val retArea = componentModelRealloc(0, 0, 8)
    Pointer(retArea.toUInt()).storeInt(ptr)
    (Pointer(retArea.toUInt()) + 4).storeInt(bytes.size)
    return retArea
}

/** Probe: is *any* scoped allocation forbidden while the host's string is still alive? */
@WasmExport("probe-scoped")
fun probeScoped(
    ptr: Int,
    len: Int,
): Int =
    try {
        kotlin.wasm.unsafe.withScopedMemoryAllocator { it.allocate(8); 1 }
    } catch (e: Throwable) {
        lastError = e.toString()
        -1
    }

/**
 * The workaround: copy the argument onto the GC heap, hand the linear memory back, *then* work.
 * If this returns a handle, the incompatibility is a discipline rather than a wall — at the price
 * of freeing memory the caller believes it still owns until `cabi_post_return`.
 */
@WasmExport("parse-gpx-freeing")
fun parseGpxFreeing(
    ptr: Int,
    len: Int,
): Int {
    val bytes = ByteArray(len)
    val base = Pointer(ptr.toUInt())
    for (i in 0 until len) bytes[i] = (base + i).loadByte()
    return try {
        kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
        val path = GpxParser.parse(bytes.decodeToString()).firstTrackAsPath()
        val handle = next++
        paths[handle] = path
        handle
    } catch (e: Throwable) {
        lastError = e.toString()
        -1
    }
}

// ---------------------------------------------------------------------------------------------
// Calling *into* a WASI 0.2 interface — the mechanics `wasi:http` would need
// ---------------------------------------------------------------------------------------------

/**
 * `wasi:random/random.get-random-bytes: func(len: u64) -> list<u8>`, called by hand.
 *
 * This is the cheapest possible component-model *import*: no argument to lower, one `list<u8>`
 * to lift. The core import is what the Canonical ABI lowers that to — the guest allocates the
 * return area and passes its pointer, the callee writes `(ptr, len)` into it.
 *
 * `wasi:http` is this, fourteen times over, with resource handles, a pollable and nested
 * `result` variants whose payload offsets have to be computed by hand. Nothing generates it.
 */
@WasmImport("wasi:random/random@0.2.7", "get-random-bytes")
private external fun getRandomBytes(
    len: Long,
    retArea: Int,
)

@WasmExport("random-sum")
fun randomSum(n: Int): Int =
    try {
        val retArea = componentModelRealloc(0, 0, 8)
        getRandomBytes(n.toLong(), retArea)
        val ptr = Pointer(retArea.toUInt()).loadInt()
        val len = (Pointer(retArea.toUInt()) + 4).loadInt()
        var sum = 0
        for (i in 0 until len) sum += (Pointer(ptr.toUInt()) + i).loadByte().toInt() and 0xFF
        // len is returned too, so the caller can tell "0 bytes" from "not called".
        len * 100000 + sum
    } catch (e: Throwable) {
        lastError = e.toString()
        -1
    }

// ---------------------------------------------------------------------------------------------
// `wasi:http/outgoing-handler` from Kotlin, by hand — the only functional gain of the whole
// Component Model exercise (task w13, step 3). One GET, status code only, no body.
// ---------------------------------------------------------------------------------------------

private const val HTTP = "wasi:http/types@0.2.7"

@WasmImport(HTTP, "[constructor]fields")
private external fun fieldsNew(): Int

@WasmImport(HTTP, "[constructor]outgoing-request")
private external fun outgoingRequestNew(headers: Int): Int

/** `set-scheme(self, option<scheme>)` — `option` flattens to a discriminant, `scheme` to three. */
@WasmImport(HTTP, "[method]outgoing-request.set-scheme")
private external fun setScheme(
    self: Int,
    isSome: Int,
    schemeDisc: Int,
    ptr: Int,
    len: Int,
): Int

@WasmImport(HTTP, "[method]outgoing-request.set-authority")
private external fun setAuthority(
    self: Int,
    isSome: Int,
    ptr: Int,
    len: Int,
): Int

@WasmImport(HTTP, "[method]outgoing-request.set-path-with-query")
private external fun setPathWithQuery(
    self: Int,
    isSome: Int,
    ptr: Int,
    len: Int,
): Int

@WasmImport("wasi:http/outgoing-handler@0.2.7", "handle")
private external fun handleRequest(
    request: Int,
    optionsSome: Int,
    options: Int,
    retArea: Int,
)

@WasmImport(HTTP, "[method]future-incoming-response.subscribe")
private external fun futureSubscribe(self: Int): Int

@WasmImport("wasi:io/poll@0.2.7", "poll")
private external fun pollList(
    ptr: Int,
    len: Int,
    retArea: Int,
)

@WasmImport(HTTP, "[method]future-incoming-response.get")
private external fun futureGet(
    self: Int,
    retArea: Int,
)

@WasmImport(HTTP, "[method]incoming-response.status")
private external fun responseStatus(self: Int): Int

private fun writeUtf8(s: String): Pair<Int, Int> {
    val bytes = s.encodeToByteArray()
    val ptr = componentModelRealloc(0, 0, bytes.size)
    for (i in bytes.indices) (Pointer(ptr.toUInt()) + i).storeByte(bytes[i])
    return ptr to bytes.size
}

/**
 * GET `https://<authority><path>` and return its HTTP status, or a negative code.
 *
 * Everything below — the flattened `option<scheme>`, the return areas whose field offsets are
 * computed by hand, the poll loop — is what `wit-bindgen` generates in one command for Rust, C,
 * Go, JS and Python, and what nothing generates for Kotlin.
 */
@WasmExport("http-get-status")
fun httpGetStatus(
    authorityPtr: Int,
    authorityLen: Int,
    pathPtr: Int,
    pathLen: Int,
): Int {
    // Copy the arguments off the caller's realloc memory before anything else can touch it.
    val authority = ByteArray(authorityLen).also { b -> for (i in 0 until authorityLen) b[i] = (Pointer(authorityPtr.toUInt()) + i).loadByte() }.decodeToString()
    val path = ByteArray(pathLen).also { b -> for (i in 0 until pathLen) b[i] = (Pointer(pathPtr.toUInt()) + i).loadByte() }.decodeToString()
    return try {
        val request = outgoingRequestNew(fieldsNew())
        // scheme: option::some(scheme::HTTPS) — HTTPS is case 1, no payload.
        check(setScheme(request, 1, 1, 0, 0) == 0) { "set-scheme refused" }
        val (aPtr, aLen) = writeUtf8(authority)
        check(setAuthority(request, 1, aPtr, aLen) == 0) { "set-authority refused" }
        val (pPtr, pLen) = writeUtf8(path)
        check(setPathWithQuery(request, 1, pPtr, pLen) == 0) { "set-path-with-query refused" }

        // Layouts below are 8-aligned with *byte* discriminants, measured with `http-debug`,
        // not read off the spec: `result<own<future-incoming-response>, error-code>` puts its
        // handle at +8, and `option<result<result<own<incoming-response>, error-code>, ()>>`
        // puts its at +24.
        val ret = componentModelRealloc(0, 0, 64)
        handleRequest(request, 0, 0, ret)
        if (Pointer(ret.toUInt()).loadByte().toInt() != 0) return -2
        val future = (Pointer(ret.toUInt()) + 8).loadInt()

        val pollable = futureSubscribe(future)
        val listPtr = componentModelRealloc(0, 0, 4)
        Pointer(listPtr.toUInt()).storeInt(pollable)
        val pollRet = componentModelRealloc(0, 0, 8)

        var rounds = 0
        while (rounds++ < 100) {
            val get = componentModelRealloc(0, 0, 64)
            futureGet(future, get)
            if (Pointer(get.toUInt()).loadByte().toInt() != 0) {
                if ((Pointer(get.toUInt()) + 8).loadByte().toInt() != 0) return -3 // future already taken
                if ((Pointer(get.toUInt()) + 16).loadByte().toInt() != 0) return -4 // err(error-code)
                return responseStatus((Pointer(get.toUInt()) + 24).loadInt())
            }
            pollList(listPtr, 1, pollRet)
        }
        -5 // never resolved
    } catch (e: Throwable) {
        lastError = e.toString()
        -1
    }
}

/** Same sequence, stopping after `step`, to find which hand-computed layout is wrong. */
@WasmExport("http-debug")
fun httpDebug(
    authorityPtr: Int,
    authorityLen: Int,
    pathPtr: Int,
    pathLen: Int,
    step: Int,
): Int {
    val authority = ByteArray(authorityLen).also { b -> for (i in 0 until authorityLen) b[i] = (Pointer(authorityPtr.toUInt()) + i).loadByte() }.decodeToString()
    val path = ByteArray(pathLen).also { b -> for (i in 0 until pathLen) b[i] = (Pointer(pathPtr.toUInt()) + i).loadByte() }.decodeToString()
    return try {
        val fields = fieldsNew()
        if (step == 1) return fields
        val request = outgoingRequestNew(fields)
        if (step == 2) return request
        val scheme = setScheme(request, 1, 1, 0, 0)
        if (step == 3) return scheme
        val (aPtr, aLen) = writeUtf8(authority)
        val auth = setAuthority(request, 1, aPtr, aLen)
        if (step == 4) return auth
        val (pPtr, pLen) = writeUtf8(path)
        val pq = setPathWithQuery(request, 1, pPtr, pLen)
        if (step == 5) return pq
        val ret = componentModelRealloc(0, 0, 32)
        for (i in 0 until 8) (Pointer(ret.toUInt()) + i * 4).storeInt(-77)
        handleRequest(request, 0, 0, ret)
        if (step in 6..13) return (Pointer(ret.toUInt()) + (step - 6) * 4).loadInt()
        // `result<own<future-incoming-response>, error-code>` is 8-aligned: a *byte* discriminant
        // at 0, the handle at 8. Measured, not deduced — step 6..13 above is how.
        if ((Pointer(ret.toUInt()).loadByte().toInt()) != 0) return -2
        val future = (Pointer(ret.toUInt()) + 8).loadInt()
        if (step == 14) return future
        val pollable = futureSubscribe(future)
        if (step == 15) return pollable
        val listPtr = componentModelRealloc(0, 0, 4)
        Pointer(listPtr.toUInt()).storeInt(pollable)
        val pollRet = componentModelRealloc(0, 0, 8)
        pollList(listPtr, 1, pollRet)
        if (step == 16) return Pointer(pollRet.toUInt()).loadInt()
        val get = componentModelRealloc(0, 0, 64)
        for (i in 0 until 16) (Pointer(get.toUInt()) + i * 4).storeInt(-77)
        futureGet(future, get)
        if (step in 17..32) return (Pointer(get.toUInt()) + (step - 17) * 4).loadInt()
        -99
    } catch (e: Throwable) {
        lastError = e.toString()
        -1
    }
}
