// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!

@file:OptIn(kotlin.wasm.unsafe.UnsafeWasmMemoryApi::class, kotlin.wasm.ExperimentalWasmInterop::class, kotlin.wasm.unsafe.ComponentModelInternalApi::class)
@file:Suppress("REDUNDANT_ELSE_IN_WHEN")

// NOTE: package name not finalized!
package io.github.glandais.engine.wit.runtime

import kotlin.wasm.unsafe.*

class ComponentException(val value: Any?) : Throwable()

sealed interface Option<out T> {
  class Some<T2>(val value: T2) : Option<T2>
  object None : Option<Nothing>
}

/**
* Handle to represent the underlying resource.
* This is an internal implementation detail and should not be used directly.
* 0 stands for a handle that does not own a rep in the RepTable.
* This can either be a newly allocated handle, or one who's ownership was transferred out of the component in a canonical ABI owning-handle lower operation.
*/
internal value class ResourceHandle(internal val value: Int) {
  companion object {
    const val DOES_NOT_OWN_REP = 0
  }
}

abstract class WitResource: AutoCloseable{
  internal var __handle: ResourceHandle
  internal constructor(handle: ResourceHandle) { __handle = handle }
  // WIT resources are lazily added into the runtime (resource-new method) and RepTable, so initially, they don't own a rep
  protected constructor() { __handle = ResourceHandle(ResourceHandle.DOES_NOT_OWN_REP) }
}

@WasmExport
fun cabi_realloc(ptr: Int, oldSize: Int, align: Int, newSize: Int): Int =
componentModelRealloc(ptr, oldSize, newSize)

fun MemoryAllocator.STRING_TO_MEM(s: String): Int =
writeToLinearMemory(s.encodeToByteArray()).address.toInt()

fun STRING_FROM_MEM(addr: Int, len: Int): String =
loadByteArray(addr.ptr, len).decodeToString()

fun MALLOC(size: Int, align: Int): Int = TODO()

val Int.ptr: Pointer
get() = Pointer(this.toUInt())

fun Pointer.loadUByte(): UByte = loadByte().toUByte()
fun Pointer.loadUShort(): UShort = loadShort().toUShort()
fun Pointer.loadUInt(): UInt = loadInt().toUInt()
fun Pointer.loadULong(): ULong = loadLong().toULong()

internal fun MemoryAllocator.writeToLinearMemory(value: String): Pointer =
writeToLinearMemory(value.encodeToByteArray())

internal fun loadString(addr: Pointer, size: Int): String =
loadByteArray(addr, size).decodeToString()
internal fun loadByteArray(addr: Pointer, size: Int): ByteArray =
ByteArray(size) { i -> (addr + i).loadByte() }
internal fun MemoryAllocator.writeToLinearMemory(array: ByteArray): Pointer {
  val pointer = allocate(array.size)
  var currentPointer = pointer
  array.forEach {
    currentPointer.storeByte(it)
    currentPointer += 1
  }
  return pointer
}


fun Pointer.loadFloat(): Float = Float.fromBits(loadInt())
fun Pointer.loadDouble(): Double = Double.fromBits(loadLong())
fun Pointer.storeFloat(value: Float) { storeInt(value.toRawBits()) }
fun Pointer.storeDouble(value: Double) { storeLong(value.toRawBits()) }

internal object RepTable {
  private val list = mutableListOf<Any>();
  private var firstVacant: Int? = null
  private data class Vacant(var next: Int?)

  fun add(v: Any): Int {
    val rep: Int
    if (firstVacant != null) {
      rep = firstVacant!!
      firstVacant = (list[rep] as Vacant).next
      list[rep] = v
    } else {
      rep = list.size
      list += v;
    }
    return rep
  }

  fun get(rep: Int): Any {
    check(list[rep] !is Vacant)
    return list[rep];
  }

  fun remove(rep: Int): Any {
    val v = get(rep)
    list[rep] = Vacant(firstVacant)
    firstVacant = rep
    return v
  }

  override fun toString(): String {
    return "RepTable(firstVacant=${firstVacant}, list = $list)"
  }
}

// Annotations
annotation class WitInterface(val package_: String)
annotation class WitImport

