// GENERATED by `./gradlew :codegen:generateTsFacade` — do not edit.
//
// Kotlin/JS emits a UMD bundle that preserves the package namespace, so the module has
// exactly one top-level export, `io`. This unwraps it once so consumers can write
// `import { enhance } from '@glandais/vcyclist-engine'`.
import * as bundle from './vcyclist-engine.js';

// `.js` in a package without "type": "module" is CommonJS, so an ESM `import *` yields
// `{ default, 'module.exports' }` and the namespace hangs off `default`. Reading `bundle.io`
// directly finds undefined, and every export below silently becomes undefined with it.
const root = bundle.default ?? bundle;
const ns = root.io?.github?.glandais?.engine ?? root;

export const parseGpxWaypoints = ns.parseGpxWaypoints;
export const parseGpx = ns.parseGpx;
export const parseGpxTracks = ns.parseGpxTracks;
export const parseGpxSegments = ns.parseGpxSegments;
export const parseGpxTracksOnly = ns.parseGpxTracksOnly;
export const parseGpxRoutesOnly = ns.parseGpxRoutesOnly;
export const writeGpxTracks = ns.writeGpxTracks;
export const pathSize = ns.pathSize;
export const pathTotalDistance = ns.pathTotalDistance;
export const pathDurationMs = ns.pathDurationMs;
export const pathElevationGain = ns.pathElevationGain;
export const pathElevationLoss = ns.pathElevationLoss;
export const pathElevationGainFiltered = ns.pathElevationGainFiltered;
export const pathElevationLossFiltered = ns.pathElevationLossFiltered;
export const pathReportedElevationGain = ns.pathReportedElevationGain;
export const pathReportedElevationLoss = ns.pathReportedElevationLoss;
export const pointAt = ns.pointAt;
export const writeGpx = ns.writeGpx;
export const writeGpxAt = ns.writeGpxAt;
export const enhance = ns.enhance;
export const enhanceWithCourse = ns.enhanceWithCourse;
export const getField = ns.getField;
export const fieldDefinitions = ns.fieldDefinitions;
export const pathLatitudeDeg = ns.pathLatitudeDeg;
export const pathLongitudeDeg = ns.pathLongitudeDeg;
export const pathToCsv = ns.pathToCsv;
export const pathToJson = ns.pathToJson;
export const pathToFit = ns.pathToFit;
export const pathsToFit = ns.pathsToFit;
export const dominantHeadwindAzimuth = ns.dominantHeadwindAzimuth;
export const dominantHeadwindAzimuthOfTracks = ns.dominantHeadwindAzimuthOfTracks;
export const detectClimbs = ns.detectClimbs;
export const detectClimbsWithOptions = ns.detectClimbsWithOptions;
export const analyzeRacingLine = ns.analyzeRacingLine;

export const climbDefaults = Object.freeze({
    minMinClimbElevationM: 10,
    maxMinClimbElevationM: 35,
    minClimbElevationRatio: 100,
    minGradePercent: 3,
    maxDiffRealGrade: 1.3,
    booster: 1.3,
    maxAnalysisPoints: 3000,
});

export const csvDefaults = Object.freeze({
    separator: ',',
    unitsInHeader: true,
    decimals: null,
    lineSeparator: '\n',
});

export const jsonDefaults = Object.freeze({
    pretty: false,
    decimals: null,
    includeMeta: true,
});
