// GENERATED by `./gradlew :codegen:generateTsFacade` — do not edit.
//
// The CommonJS half of the same unwrapping. Both spellings ship because the bundle is UMD
// and Node resolves a bare `.js` as CommonJS — an ESM-only wrapper breaks `require()`.
const root = require('./vcyclist-engine.js');

const ns = root.io?.github?.glandais?.engine ?? root;

const climbDefaults = Object.freeze({
    minMinClimbElevationM: 10,
    maxMinClimbElevationM: 35,
    minClimbElevationRatio: 100,
    minGradePercent: 3,
    maxDiffRealGrade: 1.3,
    booster: 1.3,
    maxAnalysisPoints: 3000,
});

const csvDefaults = Object.freeze({
    separator: ',',
    unitsInHeader: true,
    decimals: null,
    lineSeparator: '\n',
});

const jsonDefaults = Object.freeze({
    pretty: false,
    decimals: null,
    includeMeta: true,
});

module.exports = {
    parseGpxWaypoints: ns.parseGpxWaypoints,
    parseGpx: ns.parseGpx,
    parseGpxTracks: ns.parseGpxTracks,
    parseGpxSegments: ns.parseGpxSegments,
    parseGpxTracksOnly: ns.parseGpxTracksOnly,
    parseGpxRoutesOnly: ns.parseGpxRoutesOnly,
    writeGpxTracks: ns.writeGpxTracks,
    pathSize: ns.pathSize,
    pathTotalDistance: ns.pathTotalDistance,
    pathDurationMs: ns.pathDurationMs,
    pathElevationGain: ns.pathElevationGain,
    pathElevationLoss: ns.pathElevationLoss,
    pathElevationGainFiltered: ns.pathElevationGainFiltered,
    pathElevationLossFiltered: ns.pathElevationLossFiltered,
    pathReportedElevationGain: ns.pathReportedElevationGain,
    pathReportedElevationLoss: ns.pathReportedElevationLoss,
    pointAt: ns.pointAt,
    writeGpx: ns.writeGpx,
    writeGpxAt: ns.writeGpxAt,
    enhance: ns.enhance,
    enhanceWithCourse: ns.enhanceWithCourse,
    getField: ns.getField,
    fieldDefinitions: ns.fieldDefinitions,
    pathLatitudeDeg: ns.pathLatitudeDeg,
    pathLongitudeDeg: ns.pathLongitudeDeg,
    pathToCsv: ns.pathToCsv,
    pathToJson: ns.pathToJson,
    pathToFit: ns.pathToFit,
    pathsToFit: ns.pathsToFit,
    dominantHeadwindAzimuth: ns.dominantHeadwindAzimuth,
    dominantHeadwindAzimuthOfTracks: ns.dominantHeadwindAzimuthOfTracks,
    detectClimbs: ns.detectClimbs,
    detectClimbsWithOptions: ns.detectClimbsWithOptions,
    analyzeRacingLine: ns.analyzeRacingLine,
    climbDefaults,
    csvDefaults,
    jsonDefaults,
};
