// GENERATED by `./gradlew :codegen:generateTsFacade` — do not edit.
//
// Kotlin/JS emits a UMD bundle that preserves the package namespace, so the module has
// exactly one top-level export, `io`. This unwraps it once so consumers can write
// `import { enhance } from '@glandais/vcyclist-elevation'`.
import * as bundle from './vcyclist-elevation.js';

// `.js` in a package without "type": "module" is CommonJS, so an ESM `import *` yields
// `{ default, 'module.exports' }` and the namespace hangs off `default`. Reading `bundle.io`
// directly finds undefined, and every export below silently becomes undefined with it.
const root = bundle.default ?? bundle;
const ns = root.io?.github?.glandais?.elevation ?? root;

export const newElevationProvider = ns.newElevationProvider;
export const getElevation = ns.getElevation;
export const getElevationsAlong = ns.getElevationsAlong;
