// GENERATED by `./gradlew :codegen:generateTsFacade` — do not edit.
// Mirrors src/jsMain/kotlin/io/github/glandais/elevation/ElevationJsApi.kt.

/**
 * An opaque Kotlin/JS `ElevationProvider` instance. It is a real JS object, but it is not
 * `@JsExport`ed and has no TypeScript surface — reach into it through the
 * accessor functions below, never by property.
 *
 * Branded rather than `object` or `any` so two handle kinds cannot be swapped,
 * and so a typo dereferencing one is a compile error.
 */
declare const ElevationProviderBrand: unique symbol;
export type ElevationProvider = { readonly [ElevationProviderBrand]: 'ElevationProvider' };

/**
 * JS-side input shape `{ latitude, longitude }`.
 */
export interface CoordinatesDto {
    readonly latitude: number;
    readonly longitude: number;
}

/**
 * JS-side output shape `{ latitude, longitude, elevation }`.
 */
export interface CoordinatesElevationDto {
    readonly latitude: number;
    readonly longitude: number;
    readonly elevation: number;
}

/**
 * JS shape of `SmoothingOptions`.
 */
export interface SmoothingOptionsDto {
    readonly enabled: boolean;
    readonly windowSize: number;
}

/**
 * JS shape of `FilterOptions`.
 */
export interface FilterOptionsDto {
    readonly enabled: boolean;
    readonly tolerance: number;
    readonly zExaggeration: number;
}

/**
 * Options bag for `getElevationsAlong` — every field is optional from JS.
 */
export interface GetElevationsAlongOptionsDto {
    readonly step?: number | null;
    readonly minDistance?: number | null;
    readonly interpolation?: boolean | null;
    readonly smoothingOptions?: SmoothingOptionsDto | null;
    readonly filterOptions?: FilterOptionsDto | null;
}

/**
 * Mirrors a subset of `ElevationProviderConfig` — every field is optional from JS.
 */
export interface ElevationProviderConfigDto {
    readonly zoomLevel?: number | null;
    readonly cacheSize?: number | null;
    readonly tileUrlTemplate?: string | null;
    readonly tileSize?: number | null;
}

export declare function newElevationProvider(configDto: ElevationProviderConfigDto | null): ElevationProvider;

export declare function getElevation(provider: ElevationProvider, latitude: number, longitude: number, interpolation: boolean): Promise<number>;

export declare function getElevationsAlong(provider: ElevationProvider, path: CoordinatesDto[], options: GetElevationsAlongOptionsDto | null): Promise<CoordinatesElevationDto[]>;
