// GENERATED by `./gradlew :codegen:generateTsFacade` — do not edit.
//
// The CommonJS half of the same unwrapping. Both spellings ship because the bundle is UMD
// and Node resolves a bare `.js` as CommonJS — an ESM-only wrapper breaks `require()`.
const root = require('./vcyclist-elevation.js');

const ns = root.io?.github?.glandais?.elevation ?? root;

module.exports = {
    newElevationProvider: ns.newElevationProvider,
    getElevation: ns.getElevation,
    getElevationsAlong: ns.getElevationsAlong,
};
