// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!

@file:OptIn(kotlin.wasm.unsafe.UnsafeWasmMemoryApi::class, kotlin.wasm.ExperimentalWasmInterop::class, kotlin.wasm.unsafe.ComponentModelInternalApi::class)
@file:Suppress("REDUNDANT_ELSE_IN_WHEN")

package io.github.glandais.engine.wit


import io.github.glandais.engine.wit.runtime.*

@WitInterface("vcyclist:engine/tile-source@1.0.0")
/*external */interface TileSource {
@WitImport
companion object Import : io.github.glandais.engine.wit.TileSource {
  // <editor-fold defaultstate="collapsed" desc="Generated Import Code">
  override fun fetchTile(zoom: kotlin.UInt, x: kotlin.UInt, y: kotlin.UInt): kotlin.collections.List<kotlin.UByte>? {
    // <editor-fold defaultstate="collapsed" desc="Generated Canonical ABI Adapter Code">
    kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
      val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(3*4), align=4)*/ allocator.allocate((3*4)).address.toInt()
      __wasm_import_fetchTile(zoom.toInt(), x.toInt(), y.toInt(), ptr)
      kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory();
      // OptionLift start
      val option = if ((ptr + 0).ptr.loadUByte().toInt()== 1) {
        
        val list = kotlin.collections.ArrayList<kotlin.UByte>((ptr + (2*4)).ptr.loadInt())
        for (i in 0 until (ptr + (2*4)).ptr.loadInt()) {
          val base = ((ptr + 4).ptr.loadInt()) + (i * 1)
          
          list.add((base + 0).ptr.loadUByte().toInt().toUByte())
        }
        list
      } else {
        null
      }
      // OptionLift end
      return option
    }
    // </editor-fold>
  }
  // </editor-fold>
}
  // START OF TYPES


  // END OF TYPES

  fun fetchTile(zoom: kotlin.UInt, x: kotlin.UInt, y: kotlin.UInt): kotlin.collections.List<kotlin.UByte>?

}

@WitInterface("vcyclist:engine/types@1.0.0")
/*external */interface Types {
  // START OF TYPES


  /**
  What the four negative sentinels of ABI v1 become. The message travels *with* the error
  instead of being fetched afterwards through `vcLastError`, which disappears entirely: the
  deferred read exists only because a core function returning `i32` has nowhere to put a
  string.
  */
  sealed interface EngineError{ 
    class Failed(val value: kotlin.String) : EngineError
    object UnknownHandle : EngineError
    class InvalidArgument(val value: kotlin.String) : EngineError
    class Unsupported(val value: kotlin.String) : EngineError
  }
  /**
  §7 `vcFieldDefinitionsJson`. The `index` field of the JSON version is gone: in WIT the
  position in the returned `list` *is* the index, and `list<f64>` below is addressed by it.
  */
  class FieldDefinition(
    var prop: kotlin.String,
    var unit: kotlin.String,
    var shortDescription: kotlin.String,
    var categoryId: kotlin.String,
    var categoryName: kotlin.String,
    var notSelectable: kotlin.Boolean,
    var anglesInRadians: kotlin.Boolean,
  )

  /**
  §7 `vcPointJson` — the JS `PointDto`, field for field.
  */
  class Point(
    var latitudeDeg: kotlin.Double,
    var longitudeDeg: kotlin.Double,
    var elevation: kotlin.Double,
    var timeMs: kotlin.Double,
    var speed: kotlin.Double,
    var pComputedPower: kotlin.Double,
    var distance: kotlin.Double,
    var grade: kotlin.Double,
  )

  /**
  §7 `vcParseGpxWaypointsJson` — the JS `WaypointDto`. The `?` of the DTO becomes `option`,
  which is the one place WIT is strictly more precise than the JSON: `null` and "absent"
  stop being the same thing.
  */
  class Waypoint(
    var latitudeDeg: kotlin.Double,
    var longitudeDeg: kotlin.Double,
    var elevationM: kotlin.Double?,
    var name: kotlin.String?,
    var description: kotlin.String?,
    var symbol: kotlin.String?,
    var type: kotlin.String?,
    var timeEpochMs: kotlin.Double?,
  )

  class ClimbPart(
    var startDistanceM: kotlin.Double,
    var endDistanceM: kotlin.Double,
    var startElevationM: kotlin.Double,
    var endElevationM: kotlin.Double,
    var lengthM: kotlin.Double,
    var elevationGainM: kotlin.Double,
    var grade: kotlin.Double,
  )

  class Climb(
    var startIndex: kotlin.UInt,
    var endIndex: kotlin.UInt,
    var startDistanceM: kotlin.Double,
    var endDistanceM: kotlin.Double,
    var startElevationM: kotlin.Double,
    var endElevationM: kotlin.Double,
    var lengthM: kotlin.Double,
    var elevationGainM: kotlin.Double,
    var averageGrade: kotlin.Double,
    var climbingGrade: kotlin.Double,
    var positiveElevationM: kotlin.Double,
    var negativeElevationM: kotlin.Double,
    var parts: kotlin.collections.List<io.github.glandais.engine.wit.Types.ClimbPart>,
  )

  /**
  -----------------------------------------------------------------------------------------
  Options — replaces §9 (JSON pulled through read_input, by byte length)

  Every `option<T>` here is one line of MiniJson parsing on the guest side and one JSON
  encoder on the host side that stop existing. "Absent means the engine's default" survives
  as `option` + none; "an unknown field is an error" becomes a *type* error at binding
  generation time, which is strictly better: the typo in `mass-kg` no longer compiles.
  -----------------------------------------------------------------------------------------
  */
  class EnhanceOptions(
    var fixElevation: kotlin.Boolean?,
    var computeMaxSpeeds: kotlin.Boolean?,
    var virtualizeTrack: kotlin.Boolean?,
    var computeOnePointPerSecond: kotlin.Boolean?,
    var simplifyEnabled: kotlin.Boolean?,
    var simplifyToleranceM: kotlin.Double?,
    var simplifyZExaggeration: kotlin.Double?,
  )

  class Cyclist(
    var massKg: kotlin.Double,
    var cd: kotlin.Double,
    var frontalAreaM2: kotlin.Double,
    var maxLeanAngleDeg: kotlin.Double,
    var maxBrakeG: kotlin.Double,
    var maxSpeedKmH: kotlin.Double,
  )

  class Bike(
    var crr: kotlin.Double,
    var inertiaFront: kotlin.Double,
    var inertiaRear: kotlin.Double,
    var wheelRadiusM: kotlin.Double,
    var efficiency: kotlin.Double,
  )

  class Wind(
    /**
    m/s
    */
    var windSpeed: kotlin.Double,
    /**
    degrees, the direction the wind blows *toward* (§9)
    */
    var windDirection: kotlin.Double,
  )

  class TiringPower(
    var power: kotlin.Double,
    /**
    seconds
    */
    var tiringDuration: kotlin.Double,
  )

  /**
  §9 `power.type` is a string validated at run time and answered with -3. As a `variant` the
  three shapes carry exactly their own parameters — `tiring-duration` cannot be set on a
  constant power any more, which the JSON allows and silently ignores.
  */
  sealed interface PowerProvider{ 
    class Constant(val value: kotlin.Double) : PowerProvider
    class ConstantTiring(val value: io.github.glandais.engine.wit.Types.TiringPower) : PowerProvider
    object FromData : PowerProvider
  }
  class Course(
    var cyclist: io.github.glandais.engine.wit.Types.Cyclist?,
    var bike: io.github.glandais.engine.wit.Types.Bike?,
    var wind: io.github.glandais.engine.wit.Types.Wind?,
    var power: io.github.glandais.engine.wit.Types.PowerProvider?,
    var options: io.github.glandais.engine.wit.Types.EnhanceOptions?,
    var useHarmonics: kotlin.Boolean?,
  )

  class ClimbOptions(
    var minMinClimbElevationM: kotlin.Double?,
    var maxMinClimbElevationM: kotlin.Double?,
    var minClimbElevationRatio: kotlin.Double?,
    var minGradePercent: kotlin.Double?,
    var maxDiffRealGrade: kotlin.Double?,
    var booster: kotlin.Double?,
  )

  class GpxWriteOptions(
    var writeExtensions: kotlin.Boolean?,
    var trackName: kotlin.String?,
    var startTimeEpochMs: kotlin.Long?,
  )

  class CsvOptions(
    /**
    §9 keeps only the first character; `char` says so in the type.
    */
    var separator: kotlin.Int?,
    var unitsInHeader: kotlin.Boolean?,
    var decimals: kotlin.UByte?,
  )

  class JsonOptions(
    var pretty: kotlin.Boolean?,
    var decimals: kotlin.UByte?,
    var includeMeta: kotlin.Boolean?,
  )

  /**
  §9 `vcPathToFit`: `start-time-epoch-ms` is mandatory, which is why it is a bare field of a
  mandatory record rather than an `option`. The "0 length is refused" rule of the ABI is the
  type system's job here.
  */
  class FitOptions(
    var name: kotlin.String?,
    var startTimeEpochMs: kotlin.Long,
    var interPathGapMs: kotlin.Long?,
  )

  enum class TileFormat {
    RGBA,
    WEBP,
  }

  class TileGeometry(
    var tileSize: kotlin.UInt,
    var bytesPerPixel: kotlin.UInt,
    var expectedBytes: kotlin.UInt,
    var layout: kotlin.String,
    var encoding: kotlin.String,
    var zoomLevel: kotlin.UInt,
    var tileFormat: io.github.glandais.engine.wit.Types.TileFormat,
  )

  class ElevationConfig(
    var zoomLevel: kotlin.UInt?,
    var tileSize: kotlin.UInt?,
    var cacheSize: kotlin.UInt?,
    var tileFormat: io.github.glandais.engine.wit.Types.TileFormat?,
  )

  // END OF TYPES


}

@WitInterface("vcyclist:engine/path-api@1.0.0")
/*external */interface PathApi {
  // START OF TYPES

  /**
  The whole of §5 collapses into this. `vcRelease` becomes the resource's destructor, called
  by the caller's language (`with` in Python, `Drop` in Rust, try-with-resources in Java);
  `vcReleaseAll` becomes dropping the instance; "a released handle is never reissued"
  becomes a property of the runtime's table rather than a guest-side counter this project
  maintains and tests. A leaked handle is still a leak, but it is now the caller's leak, in
  the caller's ownership model.
  */
  abstract class Path : io.github.glandais.engine.wit.runtime.WitResource() {
    abstract fun size(): kotlin.UInt
    abstract fun totalDistance(): kotlin.Double
    abstract fun durationMs(): kotlin.Double
    abstract fun elevationGain(): kotlin.Double
    abstract fun elevationLoss(): kotlin.Double
    abstract fun latitudeDeg(index: kotlin.UInt): kotlin.Result<kotlin.Double>
    abstract fun longitudeDeg(index: kotlin.UInt): kotlin.Result<kotlin.Double>
    abstract fun dominantHeadwindAzimuth(): kotlin.Double?
    abstract fun getField(fieldIndex: kotlin.UInt, pointIndex: kotlin.UInt): kotlin.Result<kotlin.Double>
    abstract fun field(fieldIndex: kotlin.UInt): kotlin.Result<kotlin.collections.List<kotlin.Double>>
    abstract fun pointAt(index: kotlin.UInt): kotlin.Result<io.github.glandais.engine.wit.Types.Point>
    abstract fun enhance(options: io.github.glandais.engine.wit.Types.EnhanceOptions?): kotlin.Result<PathApiImpl.PathImpl>
    abstract fun enhanceWithCourse(payload: io.github.glandais.engine.wit.Types.Course): kotlin.Result<PathApiImpl.PathImpl>
    abstract fun detectClimbs(options: io.github.glandais.engine.wit.Types.ClimbOptions?): kotlin.Result<kotlin.collections.List<io.github.glandais.engine.wit.Types.Climb>>
    abstract fun writeGpx(options: io.github.glandais.engine.wit.Types.GpxWriteOptions?): kotlin.Result<kotlin.String>
    abstract fun toCsv(options: io.github.glandais.engine.wit.Types.CsvOptions?): kotlin.Result<kotlin.String>
    abstract fun toJson(options: io.github.glandais.engine.wit.Types.JsonOptions?): kotlin.Result<kotlin.String>
    abstract fun toFit(options: io.github.glandais.engine.wit.Types.FitOptions): kotlin.Result<kotlin.collections.List<kotlin.UByte>>

    // <editor-fold defaultstate="collapsed" desc="Implementation details">
    override fun close() { if(__handle.value != io.github.glandais.engine.wit.runtime.ResourceHandle.DOES_NOT_OWN_REP) __cm_resource_abi_export_PathApiImpl_Path_drop(__handle.value); __handle = io.github.glandais.engine.wit.runtime.ResourceHandle(io.github.glandais.engine.wit.runtime.ResourceHandle.DOES_NOT_OWN_REP); }
    // </editor-fold>
  }


  /**
  `vcParseGpxMulti` + `vcListSize` + `vcListGet` — three exports and a second handle table
  for what is a `list` in every language that has one. The list handle existed because a
  core export cannot return a variable number of things; here it does.

  It stays a resource rather than a plain `list<path>` only where the paths must outlive the
  call as a group (`write-gpx-tracks`, `to-fit`), and even that is expressible as
  `list<borrow<path>>` — see below. So the resource is not needed at all.
  */
  enum class ParseMode {
    /**
    tracks *and* routes
    */
    TRACKS_AND_ROUTES,
    SEGMENTS,
    TRACKS_ONLY,
    ROUTES_ONLY,
  }

  // END OF TYPES

  /**
  §4's transfer protocol in one line. `read_input`, `write_output`, the scoped arena, the
  two rules that "corrupt state rather than fail cleanly", the byte-length arguments: all of
  it is the canonical ABI's job now, generated on both sides.
  */
  fun parseGpx(gpx: kotlin.String): kotlin.Result<PathApiImpl.PathImpl>
  fun parseGpxMulti(gpx: kotlin.String, mode: io.github.glandais.engine.wit.PathApi.ParseMode): kotlin.Result<kotlin.collections.List<PathApiImpl.PathImpl>>
  fun parseGpxWaypoints(gpx: kotlin.String): kotlin.Result<kotlin.collections.List<io.github.glandais.engine.wit.Types.Waypoint>>
  fun fieldDefinitions(): kotlin.collections.List<io.github.glandais.engine.wit.Types.FieldDefinition>
  fun writeGpxTracks(paths: kotlin.collections.List<PathApiImpl.PathImpl>, options: io.github.glandais.engine.wit.Types.GpxWriteOptions?): kotlin.Result<kotlin.String>
  fun pathsToFit(paths: kotlin.collections.List<PathApiImpl.PathImpl>, options: io.github.glandais.engine.wit.Types.FitOptions): kotlin.Result<kotlin.collections.List<kotlin.UByte>>
  fun dominantHeadwindAzimuthOfTracks(paths: kotlin.collections.List<PathApiImpl.PathImpl>): kotlin.Double?

}

@WitInterface("vcyclist:engine/elevation@1.0.0")
/*external */interface Elevation {
  // START OF TYPES


  // END OF TYPES

  /**
  Sticky and validated on the spot, exactly as `vcSetElevationConfig`.
  */
  fun setConfig(config: io.github.glandais.engine.wit.Types.ElevationConfig): kotlin.Result<kotlin.Unit>
  /**
  Kept for hosts that still serve tiles themselves; with `wasi:http` it is informational.
  */
  fun geometry(): io.github.glandais.engine.wit.Types.TileGeometry

}

