// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
package io.github.glandais.engine.wit

import io.github.glandais.engine.gpx.GpxParser
import io.github.glandais.engine.gpx.firstTrackAsPath
import io.github.glandais.engine.path.Path as EnginePath

object TypesImpl : Types {

}

object PathApiImpl : PathApi {
  /**
  The whole of §5 collapses into this. `vcRelease` becomes the resource's destructor, called
  by the caller's language (`with` in Python, `Drop` in Rust, try-with-resources in Java);
  `vcReleaseAll` becomes dropping the instance; "a released handle is never reissued"
  becomes a property of the runtime's table rather than a guest-side counter this project
  maintains and tests. A leaked handle is still a leak, but it is now the caller's leak, in
  the caller's ownership model.
  */
  class PathImpl(val engine: EnginePath) : PathApi.Path() {
    override fun size(): kotlin.UInt = engine.size.toUInt()
    override fun totalDistance(): kotlin.Double = engine.totalDistance
    override fun durationMs(): kotlin.Double { TODO() }
    override fun elevationGain(): kotlin.Double { TODO() }
    override fun elevationLoss(): kotlin.Double { TODO() }
    override fun latitudeDeg(index: kotlin.UInt): kotlin.Result<kotlin.Double> { TODO() }
    override fun longitudeDeg(index: kotlin.UInt): kotlin.Result<kotlin.Double> { TODO() }
    override fun dominantHeadwindAzimuth(): kotlin.Double? { TODO() }
    override fun getField(fieldIndex: kotlin.UInt, pointIndex: kotlin.UInt): kotlin.Result<kotlin.Double> { TODO() }
    override fun field(fieldIndex: kotlin.UInt): kotlin.Result<kotlin.collections.List<kotlin.Double>> { TODO() }
    override fun pointAt(index: kotlin.UInt): kotlin.Result<io.github.glandais.engine.wit.Types.Point> { TODO() }
    override fun enhance(options: io.github.glandais.engine.wit.Types.EnhanceOptions?): kotlin.Result<PathApiImpl.PathImpl> { TODO() }
    override fun enhanceWithCourse(payload: io.github.glandais.engine.wit.Types.Course): kotlin.Result<PathApiImpl.PathImpl> { TODO() }
    override fun detectClimbs(options: io.github.glandais.engine.wit.Types.ClimbOptions?): kotlin.Result<kotlin.collections.List<io.github.glandais.engine.wit.Types.Climb>> { TODO() }
    override fun writeGpx(options: io.github.glandais.engine.wit.Types.GpxWriteOptions?): kotlin.Result<kotlin.String> { TODO() }
    override fun toCsv(options: io.github.glandais.engine.wit.Types.CsvOptions?): kotlin.Result<kotlin.String> { TODO() }
    override fun toJson(options: io.github.glandais.engine.wit.Types.JsonOptions?): kotlin.Result<kotlin.String> { TODO() }
    override fun toFit(options: io.github.glandais.engine.wit.Types.FitOptions): kotlin.Result<kotlin.collections.List<kotlin.UByte>> { TODO() }
  }

  override fun parseGpx(gpx: kotlin.String): kotlin.Result<PathApiImpl.PathImpl> =
    runCatching { PathImpl(GpxParser.parse(gpx).firstTrackAsPath()) }
  override fun parseGpxMulti(gpx: kotlin.String, mode: io.github.glandais.engine.wit.PathApi.ParseMode): kotlin.Result<kotlin.collections.List<PathApiImpl.PathImpl>> { TODO() }
  override fun parseGpxWaypoints(gpx: kotlin.String): kotlin.Result<kotlin.collections.List<io.github.glandais.engine.wit.Types.Waypoint>> { TODO() }
  override fun fieldDefinitions(): kotlin.collections.List<io.github.glandais.engine.wit.Types.FieldDefinition> { TODO() }
  override fun writeGpxTracks(paths: kotlin.collections.List<PathApiImpl.PathImpl>, options: io.github.glandais.engine.wit.Types.GpxWriteOptions?): kotlin.Result<kotlin.String> { TODO() }
  override fun pathsToFit(paths: kotlin.collections.List<PathApiImpl.PathImpl>, options: io.github.glandais.engine.wit.Types.FitOptions): kotlin.Result<kotlin.collections.List<kotlin.UByte>> { TODO() }
  override fun dominantHeadwindAzimuthOfTracks(paths: kotlin.collections.List<PathApiImpl.PathImpl>): kotlin.Double? { TODO() }

}

object ElevationImpl : Elevation {
  override fun setConfig(config: io.github.glandais.engine.wit.Types.ElevationConfig): kotlin.Result<kotlin.Unit> { TODO() }
  override fun geometry(): io.github.glandais.engine.wit.Types.TileGeometry { TODO() }

}


/*
 * Regenerate with `../generate-bindings.sh`. Three method bodies above are hand-filled — the whole
 * point of the measurement: 27 stubs, 3 implemented, and the component answers correctly.
 * Everything else in this directory is generated and must not be edited.
 */
