// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!

@file:OptIn(kotlin.wasm.unsafe.UnsafeWasmMemoryApi::class, kotlin.wasm.ExperimentalWasmInterop::class, kotlin.wasm.unsafe.ComponentModelInternalApi::class)
@file:Suppress("REDUNDANT_ELSE_IN_WHEN")

package io.github.glandais.engine.wit


import io.github.glandais.engine.wit.runtime.*


@kotlin.wasm.WasmImport("vcyclist:engine/tile-source@1.0.0", "fetch-tile")
internal external fun __wasm_import_fetchTile(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int): kotlin.Unit





@kotlin.wasm.WasmImport("[export]vcyclist:engine/path-api@1.0.0", "[resource-drop]path")
internal external fun __cm_resource_abi_export_PathApiImpl_Path_drop(handle: kotlin.Int): kotlin.Unit

@kotlin.wasm.WasmImport("[export]vcyclist:engine/path-api@1.0.0", "[resource-new]path")
internal external fun __cm_resource_abi_export_PathApiImpl_Path_new(handle: kotlin.Int): kotlin.Int

@kotlin.wasm.WasmImport("[export]vcyclist:engine/path-api@1.0.0", "[resource-rep]path")
internal external fun __cm_resource_abi_export_PathApiImpl_Path_rep(handle: kotlin.Int): kotlin.Int

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#dtor[path]")
internal fun __wasm_export_path_dtor(rep: kotlin.Int) {
  val resource = io.github.glandais.engine.wit.runtime.RepTable.remove(rep) as io.github.glandais.engine.wit.runtime.WitResource
  resource.__handle = io.github.glandais.engine.wit.runtime.ResourceHandle(io.github.glandais.engine.wit.runtime.ResourceHandle.DOES_NOT_OWN_REP)
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#[method]path.size")
fun __wasm_export_size(p0: kotlin.Int): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val resource = io.github.glandais.engine.wit.runtime.RepTable.get(p0) as PathApiImpl.PathImpl
  val result: kotlin.UInt = resource.size()

  return result.toInt()
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#[method]path.total-distance")
fun __wasm_export_totalDistance(p0: kotlin.Int): kotlin.Double {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val resource = io.github.glandais.engine.wit.runtime.RepTable.get(p0) as PathApiImpl.PathImpl
  val result: kotlin.Double = resource.totalDistance()

  return result
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#[method]path.duration-ms")
fun __wasm_export_durationMs(p0: kotlin.Int): kotlin.Double {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val resource = io.github.glandais.engine.wit.runtime.RepTable.get(p0) as PathApiImpl.PathImpl
  val result: kotlin.Double = resource.durationMs()

  return result
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#[method]path.elevation-gain")
fun __wasm_export_elevationGain(p0: kotlin.Int): kotlin.Double {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val resource = io.github.glandais.engine.wit.runtime.RepTable.get(p0) as PathApiImpl.PathImpl
  val result: kotlin.Double = resource.elevationGain()

  return result
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#[method]path.elevation-loss")
fun __wasm_export_elevationLoss(p0: kotlin.Int): kotlin.Double {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val resource = io.github.glandais.engine.wit.runtime.RepTable.get(p0) as PathApiImpl.PathImpl
  val result: kotlin.Double = resource.elevationLoss()

  return result
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#[method]path.latitude-deg")
fun __wasm_export_latitudeDeg(p0: kotlin.Int, p1: kotlin.Int): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val resource = io.github.glandais.engine.wit.runtime.RepTable.get(p0) as PathApiImpl.PathImpl
  val result: kotlin.Result<kotlin.Double> = resource.latitudeDeg(p1.toUInt())

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(16+2*4), align=8)*/ allocator.allocate((16+2*4)).address.toInt()
  if (result.isFailure) {
    val payload0 = (result.exceptionOrNull() as io.github.glandais.engine.wit.runtime.ComponentException).value as io.github.glandais.engine.wit.Types.EngineError
    (ptr + 0).ptr.storeByte(1.toByte())
    // VariantLower START
    when (val x = payload0) {
      is io.github.glandais.engine.wit.Types.EngineError.Failed -> {
        val payload1 = x.value
        (ptr + 8).ptr.storeByte(0.toByte())

        val bytearray = payload1.encodeToByteArray()
        val len = bytearray.size
        val ptr2 = allocator.writeToLinearMemory(bytearray).address.toInt()

        (ptr + (8+2*4)).ptr.storeInt(len)
        (ptr + (8+1*4)).ptr.storeInt(ptr2)
      }
      is io.github.glandais.engine.wit.Types.EngineError.UnknownHandle -> {
        (ptr + 8).ptr.storeByte(1.toByte())
      }
      is io.github.glandais.engine.wit.Types.EngineError.InvalidArgument -> {
        val payload4 = x.value
        (ptr + 8).ptr.storeByte(2.toByte())

        val bytearray7 = payload4.encodeToByteArray()
        val len6 = bytearray7.size
        val ptr5 = allocator.writeToLinearMemory(bytearray7).address.toInt()

        (ptr + (8+2*4)).ptr.storeInt(len6)
        (ptr + (8+1*4)).ptr.storeInt(ptr5)
      }
      is io.github.glandais.engine.wit.Types.EngineError.Unsupported -> {
        val payload8 = x.value
        (ptr + 8).ptr.storeByte(3.toByte())

        val bytearray11 = payload8.encodeToByteArray()
        val len10 = bytearray11.size
        val ptr9 = allocator.writeToLinearMemory(bytearray11).address.toInt()

        (ptr + (8+2*4)).ptr.storeInt(len10)
        (ptr + (8+1*4)).ptr.storeInt(ptr9)
      }
      else -> error("unreachable")
    }
    // VariantLower END
  } else {
    val payload = result.getOrThrow()!!
    (ptr + 0).ptr.storeByte(0.toByte())
    (ptr + 8).ptr.storeDouble(payload)
  }
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#[method]path.longitude-deg")
fun __wasm_export_longitudeDeg(p0: kotlin.Int, p1: kotlin.Int): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val resource = io.github.glandais.engine.wit.runtime.RepTable.get(p0) as PathApiImpl.PathImpl
  val result: kotlin.Result<kotlin.Double> = resource.longitudeDeg(p1.toUInt())

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(16+2*4), align=8)*/ allocator.allocate((16+2*4)).address.toInt()
  if (result.isFailure) {
    val payload0 = (result.exceptionOrNull() as io.github.glandais.engine.wit.runtime.ComponentException).value as io.github.glandais.engine.wit.Types.EngineError
    (ptr + 0).ptr.storeByte(1.toByte())
    // VariantLower START
    when (val x = payload0) {
      is io.github.glandais.engine.wit.Types.EngineError.Failed -> {
        val payload1 = x.value
        (ptr + 8).ptr.storeByte(0.toByte())

        val bytearray = payload1.encodeToByteArray()
        val len = bytearray.size
        val ptr2 = allocator.writeToLinearMemory(bytearray).address.toInt()

        (ptr + (8+2*4)).ptr.storeInt(len)
        (ptr + (8+1*4)).ptr.storeInt(ptr2)
      }
      is io.github.glandais.engine.wit.Types.EngineError.UnknownHandle -> {
        (ptr + 8).ptr.storeByte(1.toByte())
      }
      is io.github.glandais.engine.wit.Types.EngineError.InvalidArgument -> {
        val payload4 = x.value
        (ptr + 8).ptr.storeByte(2.toByte())

        val bytearray7 = payload4.encodeToByteArray()
        val len6 = bytearray7.size
        val ptr5 = allocator.writeToLinearMemory(bytearray7).address.toInt()

        (ptr + (8+2*4)).ptr.storeInt(len6)
        (ptr + (8+1*4)).ptr.storeInt(ptr5)
      }
      is io.github.glandais.engine.wit.Types.EngineError.Unsupported -> {
        val payload8 = x.value
        (ptr + 8).ptr.storeByte(3.toByte())

        val bytearray11 = payload8.encodeToByteArray()
        val len10 = bytearray11.size
        val ptr9 = allocator.writeToLinearMemory(bytearray11).address.toInt()

        (ptr + (8+2*4)).ptr.storeInt(len10)
        (ptr + (8+1*4)).ptr.storeInt(ptr9)
      }
      else -> error("unreachable")
    }
    // VariantLower END
  } else {
    val payload = result.getOrThrow()!!
    (ptr + 0).ptr.storeByte(0.toByte())
    (ptr + 8).ptr.storeDouble(payload)
  }
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#[method]path.dominant-headwind-azimuth")
fun __wasm_export_dominantHeadwindAzimuth(p0: kotlin.Int): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val resource = io.github.glandais.engine.wit.runtime.RepTable.get(p0) as PathApiImpl.PathImpl
  val result: kotlin.Double? = resource.dominantHeadwindAzimuth()

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=16, align=8)*/ allocator.allocate(16).address.toInt()
  val payload0 = result
  if (payload0 != null) {
    (ptr + 0).ptr.storeByte(1.toByte())
    (ptr + 8).ptr.storeDouble(payload0)
  } else {
    (ptr + 0).ptr.storeByte(0.toByte())
  }
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#[method]path.get-field")
fun __wasm_export_getField(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val resource = io.github.glandais.engine.wit.runtime.RepTable.get(p0) as PathApiImpl.PathImpl
  val result: kotlin.Result<kotlin.Double> = resource.getField(p1.toUInt(), p2.toUInt())

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(16+2*4), align=8)*/ allocator.allocate((16+2*4)).address.toInt()
  if (result.isFailure) {
    val payload0 = (result.exceptionOrNull() as io.github.glandais.engine.wit.runtime.ComponentException).value as io.github.glandais.engine.wit.Types.EngineError
    (ptr + 0).ptr.storeByte(1.toByte())
    // VariantLower START
    when (val x = payload0) {
      is io.github.glandais.engine.wit.Types.EngineError.Failed -> {
        val payload1 = x.value
        (ptr + 8).ptr.storeByte(0.toByte())

        val bytearray = payload1.encodeToByteArray()
        val len = bytearray.size
        val ptr2 = allocator.writeToLinearMemory(bytearray).address.toInt()

        (ptr + (8+2*4)).ptr.storeInt(len)
        (ptr + (8+1*4)).ptr.storeInt(ptr2)
      }
      is io.github.glandais.engine.wit.Types.EngineError.UnknownHandle -> {
        (ptr + 8).ptr.storeByte(1.toByte())
      }
      is io.github.glandais.engine.wit.Types.EngineError.InvalidArgument -> {
        val payload4 = x.value
        (ptr + 8).ptr.storeByte(2.toByte())

        val bytearray7 = payload4.encodeToByteArray()
        val len6 = bytearray7.size
        val ptr5 = allocator.writeToLinearMemory(bytearray7).address.toInt()

        (ptr + (8+2*4)).ptr.storeInt(len6)
        (ptr + (8+1*4)).ptr.storeInt(ptr5)
      }
      is io.github.glandais.engine.wit.Types.EngineError.Unsupported -> {
        val payload8 = x.value
        (ptr + 8).ptr.storeByte(3.toByte())

        val bytearray11 = payload8.encodeToByteArray()
        val len10 = bytearray11.size
        val ptr9 = allocator.writeToLinearMemory(bytearray11).address.toInt()

        (ptr + (8+2*4)).ptr.storeInt(len10)
        (ptr + (8+1*4)).ptr.storeInt(ptr9)
      }
      else -> error("unreachable")
    }
    // VariantLower END
  } else {
    val payload = result.getOrThrow()!!
    (ptr + 0).ptr.storeByte(0.toByte())
    (ptr + 8).ptr.storeDouble(payload)
  }
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#[method]path.field")
fun __wasm_export_field(p0: kotlin.Int, p1: kotlin.Int): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val resource = io.github.glandais.engine.wit.runtime.RepTable.get(p0) as PathApiImpl.PathImpl
  val result: kotlin.Result<kotlin.collections.List<kotlin.Double>> = resource.field(p1.toUInt())

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(4*4), align=4)*/ allocator.allocate((4*4)).address.toInt()
  if (result.isFailure) {
    val payload0 = (result.exceptionOrNull() as io.github.glandais.engine.wit.runtime.ComponentException).value as io.github.glandais.engine.wit.Types.EngineError
    (ptr + 0).ptr.storeByte(1.toByte())
    // VariantLower START
    when (val x = payload0) {
      is io.github.glandais.engine.wit.Types.EngineError.Failed -> {
        val payload1 = x.value
        (ptr + 4).ptr.storeByte(0.toByte())

        val bytearray = payload1.encodeToByteArray()
        val len = bytearray.size
        val ptr2 = allocator.writeToLinearMemory(bytearray).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len)
        (ptr + (2*4)).ptr.storeInt(ptr2)
      }
      is io.github.glandais.engine.wit.Types.EngineError.UnknownHandle -> {
        (ptr + 4).ptr.storeByte(1.toByte())
      }
      is io.github.glandais.engine.wit.Types.EngineError.InvalidArgument -> {
        val payload4 = x.value
        (ptr + 4).ptr.storeByte(2.toByte())

        val bytearray7 = payload4.encodeToByteArray()
        val len6 = bytearray7.size
        val ptr5 = allocator.writeToLinearMemory(bytearray7).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len6)
        (ptr + (2*4)).ptr.storeInt(ptr5)
      }
      is io.github.glandais.engine.wit.Types.EngineError.Unsupported -> {
        val payload8 = x.value
        (ptr + 4).ptr.storeByte(3.toByte())

        val bytearray11 = payload8.encodeToByteArray()
        val len10 = bytearray11.size
        val ptr9 = allocator.writeToLinearMemory(bytearray11).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len10)
        (ptr + (2*4)).ptr.storeInt(ptr9)
      }
      else -> error("unreachable")
    }
    // VariantLower END
  } else {
    val payload = result.getOrThrow()!!
    (ptr + 0).ptr.storeByte(0.toByte())

    val address = allocator.allocate(payload.size * 8 /*, align_wasm32=8*/).address.toInt()
    for (iter in payload.withIndex()) {
      val index = iter.index
      val el = iter.value
      val base = address + (index * 8)
      (base + 0).ptr.storeDouble(el)

    }
    (ptr + (2*4)).ptr.storeInt(payload.size)
    (ptr + 4).ptr.storeInt(address)
  }
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#[method]path.point-at")
fun __wasm_export_pointAt(p0: kotlin.Int, p1: kotlin.Int): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val resource = io.github.glandais.engine.wit.runtime.RepTable.get(p0) as PathApiImpl.PathImpl
  val result: kotlin.Result<io.github.glandais.engine.wit.Types.Point> = resource.pointAt(p1.toUInt())

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=72, align=8)*/ allocator.allocate(72).address.toInt()
  if (result.isFailure) {
    val payload0 = (result.exceptionOrNull() as io.github.glandais.engine.wit.runtime.ComponentException).value as io.github.glandais.engine.wit.Types.EngineError
    (ptr + 0).ptr.storeByte(1.toByte())
    // VariantLower START
    when (val x = payload0) {
      is io.github.glandais.engine.wit.Types.EngineError.Failed -> {
        val payload1 = x.value
        (ptr + 8).ptr.storeByte(0.toByte())

        val bytearray = payload1.encodeToByteArray()
        val len = bytearray.size
        val ptr2 = allocator.writeToLinearMemory(bytearray).address.toInt()

        (ptr + (8+2*4)).ptr.storeInt(len)
        (ptr + (8+1*4)).ptr.storeInt(ptr2)
      }
      is io.github.glandais.engine.wit.Types.EngineError.UnknownHandle -> {
        (ptr + 8).ptr.storeByte(1.toByte())
      }
      is io.github.glandais.engine.wit.Types.EngineError.InvalidArgument -> {
        val payload4 = x.value
        (ptr + 8).ptr.storeByte(2.toByte())

        val bytearray7 = payload4.encodeToByteArray()
        val len6 = bytearray7.size
        val ptr5 = allocator.writeToLinearMemory(bytearray7).address.toInt()

        (ptr + (8+2*4)).ptr.storeInt(len6)
        (ptr + (8+1*4)).ptr.storeInt(ptr5)
      }
      is io.github.glandais.engine.wit.Types.EngineError.Unsupported -> {
        val payload8 = x.value
        (ptr + 8).ptr.storeByte(3.toByte())

        val bytearray11 = payload8.encodeToByteArray()
        val len10 = bytearray11.size
        val ptr9 = allocator.writeToLinearMemory(bytearray11).address.toInt()

        (ptr + (8+2*4)).ptr.storeInt(len10)
        (ptr + (8+1*4)).ptr.storeInt(ptr9)
      }
      else -> error("unreachable")
    }
    // VariantLower END
  } else {
    val payload = result.getOrThrow()!!
    (ptr + 0).ptr.storeByte(0.toByte())
    (ptr + 8).ptr.storeDouble(payload.latitudeDeg)
    (ptr + 16).ptr.storeDouble(payload.longitudeDeg)
    (ptr + 24).ptr.storeDouble(payload.elevation)
    (ptr + 32).ptr.storeDouble(payload.timeMs)
    (ptr + 40).ptr.storeDouble(payload.speed)
    (ptr + 48).ptr.storeDouble(payload.pComputedPower)
    (ptr + 56).ptr.storeDouble(payload.distance)
    (ptr + 64).ptr.storeDouble(payload.grade)
  }
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#[method]path.enhance")
fun __wasm_export_enhance(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int, p4: kotlin.Int, p5: kotlin.Int, p6: kotlin.Int, p7: kotlin.Int, p8: kotlin.Int, p9: kotlin.Int, p10: kotlin.Int, p11: kotlin.Int, p12: kotlin.Int, p13: kotlin.Double, p14: kotlin.Int, p15: kotlin.Double): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val resource = io.github.glandais.engine.wit.runtime.RepTable.get(p0) as PathApiImpl.PathImpl
  // OptionLift start
  val option6 = if (p1== 1) {
    // OptionLift start
    val option = if (p2== 1) {
      (p3 != 0)
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option0 = if (p4== 1) {
      (p5 != 0)
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option1 = if (p6== 1) {
      (p7 != 0)
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option2 = if (p8== 1) {
      (p9 != 0)
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option3 = if (p10== 1) {
      (p11 != 0)
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option4 = if (p12== 1) {
      p13
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option5 = if (p14== 1) {
      p15
    } else {
      null
    }
    // OptionLift end
    io.github.glandais.engine.wit.Types.EnhanceOptions(
    option,
    option0,
    option1,
    option2,
    option3,
    option4,
    option5,
    )
  } else {
    null
  }
  // OptionLift end
  val result: kotlin.Result<PathApiImpl.PathImpl> = resource.enhance(option6)

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(4*4), align=4)*/ allocator.allocate((4*4)).address.toInt()
  if (result.isFailure) {
    val payload7 = (result.exceptionOrNull() as io.github.glandais.engine.wit.runtime.ComponentException).value as io.github.glandais.engine.wit.Types.EngineError
    (ptr + 0).ptr.storeByte(1.toByte())
    // VariantLower START
    when (val x = payload7) {
      is io.github.glandais.engine.wit.Types.EngineError.Failed -> {
        val payload8 = x.value
        (ptr + 4).ptr.storeByte(0.toByte())

        val bytearray = payload8.encodeToByteArray()
        val len = bytearray.size
        val ptr9 = allocator.writeToLinearMemory(bytearray).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len)
        (ptr + (2*4)).ptr.storeInt(ptr9)
      }
      is io.github.glandais.engine.wit.Types.EngineError.UnknownHandle -> {
        (ptr + 4).ptr.storeByte(1.toByte())
      }
      is io.github.glandais.engine.wit.Types.EngineError.InvalidArgument -> {
        val payload11 = x.value
        (ptr + 4).ptr.storeByte(2.toByte())

        val bytearray14 = payload11.encodeToByteArray()
        val len13 = bytearray14.size
        val ptr12 = allocator.writeToLinearMemory(bytearray14).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len13)
        (ptr + (2*4)).ptr.storeInt(ptr12)
      }
      is io.github.glandais.engine.wit.Types.EngineError.Unsupported -> {
        val payload15 = x.value
        (ptr + 4).ptr.storeByte(3.toByte())

        val bytearray18 = payload15.encodeToByteArray()
        val len17 = bytearray18.size
        val ptr16 = allocator.writeToLinearMemory(bytearray18).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len17)
        (ptr + (2*4)).ptr.storeInt(ptr16)
      }
      else -> error("unreachable")
    }
    // VariantLower END
  } else {
    val payload = result.getOrThrow()!!
    (ptr + 0).ptr.storeByte(0.toByte())
    var handle = payload.__handle.value;
    if (handle == io.github.glandais.engine.wit.runtime.ResourceHandle.DOES_NOT_OWN_REP) {
      var localRep = io.github.glandais.engine.wit.runtime.RepTable.add(payload);
      handle = __cm_resource_abi_export_PathApiImpl_Path_new(localRep);
    }

    payload.__handle = io.github.glandais.engine.wit.runtime.ResourceHandle(0);
    (ptr + 4).ptr.storeInt(handle)
  }
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#[method]path.enhance-with-course")
fun __wasm_export_enhanceWithCourse(p0: kotlin.Int): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val resource = io.github.glandais.engine.wit.runtime.RepTable.get((p0 + 0).ptr.loadInt()) as PathApiImpl.PathImpl
  // OptionLift start
  val option = if ((p0 + 8).ptr.loadUByte().toInt()== 1) {
    io.github.glandais.engine.wit.Types.Cyclist(
    (p0 + 16).ptr.loadDouble(),
    (p0 + 24).ptr.loadDouble(),
    (p0 + 32).ptr.loadDouble(),
    (p0 + 40).ptr.loadDouble(),
    (p0 + 48).ptr.loadDouble(),
    (p0 + 56).ptr.loadDouble(),
    )
  } else {
    null
  }
  // OptionLift end
  // OptionLift start
  val option0 = if ((p0 + 64).ptr.loadUByte().toInt()== 1) {
    io.github.glandais.engine.wit.Types.Bike(
    (p0 + 72).ptr.loadDouble(),
    (p0 + 80).ptr.loadDouble(),
    (p0 + 88).ptr.loadDouble(),
    (p0 + 96).ptr.loadDouble(),
    (p0 + 104).ptr.loadDouble(),
    )
  } else {
    null
  }
  // OptionLift end
  // OptionLift start
  val option1 = if ((p0 + 112).ptr.loadUByte().toInt()== 1) {
    io.github.glandais.engine.wit.Types.Wind(
    (p0 + 120).ptr.loadDouble(),
    (p0 + 128).ptr.loadDouble(),
    )
  } else {
    null
  }
  // OptionLift end
  // OptionLift start
  val option2 = if ((p0 + 136).ptr.loadUByte().toInt()== 1) {
    // VariantLift START.
    val variant = when ((p0 + 144).ptr.loadUByte().toInt()) {
      0 -> {
        io.github.glandais.engine.wit.Types.PowerProvider.Constant((p0 + 152).ptr.loadDouble())
      }
      1 -> {
        io.github.glandais.engine.wit.Types.PowerProvider.ConstantTiring(io.github.glandais.engine.wit.Types.TiringPower(
        (p0 + 152).ptr.loadDouble(),
        (p0 + 160).ptr.loadDouble(),
        ))
      }
      2 -> {
        io.github.glandais.engine.wit.Types.PowerProvider.FromData
      }
      else -> error("unreachable")
    }
    // VariantLift END
    variant
  } else {
    null
  }
  // OptionLift end
  // OptionLift start
  val option10 = if ((p0 + 168).ptr.loadUByte().toInt()== 1) {
    // OptionLift start
    val option3 = if ((p0 + 176).ptr.loadUByte().toInt()== 1) {
      ((p0 + 177).ptr.loadUByte().toInt() != 0)
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option4 = if ((p0 + 178).ptr.loadUByte().toInt()== 1) {
      ((p0 + 179).ptr.loadUByte().toInt() != 0)
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option5 = if ((p0 + 180).ptr.loadUByte().toInt()== 1) {
      ((p0 + 181).ptr.loadUByte().toInt() != 0)
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option6 = if ((p0 + 182).ptr.loadUByte().toInt()== 1) {
      ((p0 + 183).ptr.loadUByte().toInt() != 0)
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option7 = if ((p0 + 184).ptr.loadUByte().toInt()== 1) {
      ((p0 + 185).ptr.loadUByte().toInt() != 0)
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option8 = if ((p0 + 192).ptr.loadUByte().toInt()== 1) {
      (p0 + 200).ptr.loadDouble()
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option9 = if ((p0 + 208).ptr.loadUByte().toInt()== 1) {
      (p0 + 216).ptr.loadDouble()
    } else {
      null
    }
    // OptionLift end
    io.github.glandais.engine.wit.Types.EnhanceOptions(
    option3,
    option4,
    option5,
    option6,
    option7,
    option8,
    option9,
    )
  } else {
    null
  }
  // OptionLift end
  // OptionLift start
  val option11 = if ((p0 + 224).ptr.loadUByte().toInt()== 1) {
    ((p0 + 225).ptr.loadUByte().toInt() != 0)
  } else {
    null
  }
  // OptionLift end
  val result: kotlin.Result<PathApiImpl.PathImpl> = resource.enhanceWithCourse(io.github.glandais.engine.wit.Types.Course(
  option,
  option0,
  option1,
  option2,
  option10,
  option11,
  ))

  // GuestDeallocate(p0)
  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(4*4), align=4)*/ allocator.allocate((4*4)).address.toInt()
  if (result.isFailure) {
    val payload12 = (result.exceptionOrNull() as io.github.glandais.engine.wit.runtime.ComponentException).value as io.github.glandais.engine.wit.Types.EngineError
    (ptr + 0).ptr.storeByte(1.toByte())
    // VariantLower START
    when (val x = payload12) {
      is io.github.glandais.engine.wit.Types.EngineError.Failed -> {
        val payload13 = x.value
        (ptr + 4).ptr.storeByte(0.toByte())

        val bytearray = payload13.encodeToByteArray()
        val len = bytearray.size
        val ptr14 = allocator.writeToLinearMemory(bytearray).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len)
        (ptr + (2*4)).ptr.storeInt(ptr14)
      }
      is io.github.glandais.engine.wit.Types.EngineError.UnknownHandle -> {
        (ptr + 4).ptr.storeByte(1.toByte())
      }
      is io.github.glandais.engine.wit.Types.EngineError.InvalidArgument -> {
        val payload16 = x.value
        (ptr + 4).ptr.storeByte(2.toByte())

        val bytearray19 = payload16.encodeToByteArray()
        val len18 = bytearray19.size
        val ptr17 = allocator.writeToLinearMemory(bytearray19).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len18)
        (ptr + (2*4)).ptr.storeInt(ptr17)
      }
      is io.github.glandais.engine.wit.Types.EngineError.Unsupported -> {
        val payload20 = x.value
        (ptr + 4).ptr.storeByte(3.toByte())

        val bytearray23 = payload20.encodeToByteArray()
        val len22 = bytearray23.size
        val ptr21 = allocator.writeToLinearMemory(bytearray23).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len22)
        (ptr + (2*4)).ptr.storeInt(ptr21)
      }
      else -> error("unreachable")
    }
    // VariantLower END
  } else {
    val payload = result.getOrThrow()!!
    (ptr + 0).ptr.storeByte(0.toByte())
    var handle = payload.__handle.value;
    if (handle == io.github.glandais.engine.wit.runtime.ResourceHandle.DOES_NOT_OWN_REP) {
      var localRep = io.github.glandais.engine.wit.runtime.RepTable.add(payload);
      handle = __cm_resource_abi_export_PathApiImpl_Path_new(localRep);
    }

    payload.__handle = io.github.glandais.engine.wit.runtime.ResourceHandle(0);
    (ptr + 4).ptr.storeInt(handle)
  }
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#[method]path.detect-climbs")
fun __wasm_export_detectClimbs(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Double, p4: kotlin.Int, p5: kotlin.Double, p6: kotlin.Int, p7: kotlin.Double, p8: kotlin.Int, p9: kotlin.Double, p10: kotlin.Int, p11: kotlin.Double, p12: kotlin.Int, p13: kotlin.Double): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val resource = io.github.glandais.engine.wit.runtime.RepTable.get(p0) as PathApiImpl.PathImpl
  // OptionLift start
  val option5 = if (p1== 1) {
    // OptionLift start
    val option = if (p2== 1) {
      p3
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option0 = if (p4== 1) {
      p5
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option1 = if (p6== 1) {
      p7
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option2 = if (p8== 1) {
      p9
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option3 = if (p10== 1) {
      p11
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option4 = if (p12== 1) {
      p13
    } else {
      null
    }
    // OptionLift end
    io.github.glandais.engine.wit.Types.ClimbOptions(
    option,
    option0,
    option1,
    option2,
    option3,
    option4,
    )
  } else {
    null
  }
  // OptionLift end
  val result: kotlin.Result<kotlin.collections.List<io.github.glandais.engine.wit.Types.Climb>> = resource.detectClimbs(option5)

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(4*4), align=4)*/ allocator.allocate((4*4)).address.toInt()
  if (result.isFailure) {
    val payload9 = (result.exceptionOrNull() as io.github.glandais.engine.wit.runtime.ComponentException).value as io.github.glandais.engine.wit.Types.EngineError
    (ptr + 0).ptr.storeByte(1.toByte())
    // VariantLower START
    when (val x = payload9) {
      is io.github.glandais.engine.wit.Types.EngineError.Failed -> {
        val payload10 = x.value
        (ptr + 4).ptr.storeByte(0.toByte())

        val bytearray = payload10.encodeToByteArray()
        val len = bytearray.size
        val ptr11 = allocator.writeToLinearMemory(bytearray).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len)
        (ptr + (2*4)).ptr.storeInt(ptr11)
      }
      is io.github.glandais.engine.wit.Types.EngineError.UnknownHandle -> {
        (ptr + 4).ptr.storeByte(1.toByte())
      }
      is io.github.glandais.engine.wit.Types.EngineError.InvalidArgument -> {
        val payload13 = x.value
        (ptr + 4).ptr.storeByte(2.toByte())

        val bytearray16 = payload13.encodeToByteArray()
        val len15 = bytearray16.size
        val ptr14 = allocator.writeToLinearMemory(bytearray16).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len15)
        (ptr + (2*4)).ptr.storeInt(ptr14)
      }
      is io.github.glandais.engine.wit.Types.EngineError.Unsupported -> {
        val payload17 = x.value
        (ptr + 4).ptr.storeByte(3.toByte())

        val bytearray20 = payload17.encodeToByteArray()
        val len19 = bytearray20.size
        val ptr18 = allocator.writeToLinearMemory(bytearray20).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len19)
        (ptr + (2*4)).ptr.storeInt(ptr18)
      }
      else -> error("unreachable")
    }
    // VariantLower END
  } else {
    val payload = result.getOrThrow()!!
    (ptr + 0).ptr.storeByte(0.toByte())

    val address6 = allocator.allocate(payload.size * (88+2*4) /*, align_wasm32=8*/).address.toInt()
    for (iter7 in payload.withIndex()) {
      val index8 = iter7.index
      val el = iter7.value
      val base = address6 + (index8 * (88+2*4))
      (base + 0).ptr.storeInt(el.startIndex.toInt())
      (base + 4).ptr.storeInt(el.endIndex.toInt())
      (base + 8).ptr.storeDouble(el.startDistanceM)
      (base + 16).ptr.storeDouble(el.endDistanceM)
      (base + 24).ptr.storeDouble(el.startElevationM)
      (base + 32).ptr.storeDouble(el.endElevationM)
      (base + 40).ptr.storeDouble(el.lengthM)
      (base + 48).ptr.storeDouble(el.elevationGainM)
      (base + 56).ptr.storeDouble(el.averageGrade)
      (base + 64).ptr.storeDouble(el.climbingGrade)
      (base + 72).ptr.storeDouble(el.positiveElevationM)
      (base + 80).ptr.storeDouble(el.negativeElevationM)

      val address = allocator.allocate(el.parts.size * 56 /*, align_wasm32=8*/).address.toInt()
      for (iter in el.parts.withIndex()) {
        val index = iter.index
        val el = iter.value
        val base = address + (index * 56)
        (base + 0).ptr.storeDouble(el.startDistanceM)
        (base + 8).ptr.storeDouble(el.endDistanceM)
        (base + 16).ptr.storeDouble(el.startElevationM)
        (base + 24).ptr.storeDouble(el.endElevationM)
        (base + 32).ptr.storeDouble(el.lengthM)
        (base + 40).ptr.storeDouble(el.elevationGainM)
        (base + 48).ptr.storeDouble(el.grade)

      }
      (base + (88+1*4)).ptr.storeInt(el.parts.size)
      (base + 88).ptr.storeInt(address)

    }
    (ptr + (2*4)).ptr.storeInt(payload.size)
    (ptr + 4).ptr.storeInt(address6)
  }
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#[method]path.write-gpx")
fun __wasm_export_writeGpx(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int, p4: kotlin.Int, p5: kotlin.Int, p6: kotlin.Int, p7: kotlin.Int, p8: kotlin.Long): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val resource = io.github.glandais.engine.wit.runtime.RepTable.get(p0) as PathApiImpl.PathImpl
  // OptionLift start
  val option2 = if (p1== 1) {
    // OptionLift start
    val option = if (p2== 1) {
      (p3 != 0)
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option0 = if (p4== 1) {
      io.github.glandais.engine.wit.runtime.STRING_FROM_MEM(p5, p6)
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option1 = if (p7== 1) {
      p8
    } else {
      null
    }
    // OptionLift end
    io.github.glandais.engine.wit.Types.GpxWriteOptions(
    option,
    option0,
    option1,
    )
  } else {
    null
  }
  // OptionLift end
  val result: kotlin.Result<kotlin.String> = resource.writeGpx(option2)

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(4*4), align=4)*/ allocator.allocate((4*4)).address.toInt()
  if (result.isFailure) {
    val payload4 = (result.exceptionOrNull() as io.github.glandais.engine.wit.runtime.ComponentException).value as io.github.glandais.engine.wit.Types.EngineError
    (ptr + 0).ptr.storeByte(1.toByte())
    // VariantLower START
    when (val x = payload4) {
      is io.github.glandais.engine.wit.Types.EngineError.Failed -> {
        val payload5 = x.value
        (ptr + 4).ptr.storeByte(0.toByte())

        val bytearray8 = payload5.encodeToByteArray()
        val len7 = bytearray8.size
        val ptr6 = allocator.writeToLinearMemory(bytearray8).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len7)
        (ptr + (2*4)).ptr.storeInt(ptr6)
      }
      is io.github.glandais.engine.wit.Types.EngineError.UnknownHandle -> {
        (ptr + 4).ptr.storeByte(1.toByte())
      }
      is io.github.glandais.engine.wit.Types.EngineError.InvalidArgument -> {
        val payload10 = x.value
        (ptr + 4).ptr.storeByte(2.toByte())

        val bytearray13 = payload10.encodeToByteArray()
        val len12 = bytearray13.size
        val ptr11 = allocator.writeToLinearMemory(bytearray13).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len12)
        (ptr + (2*4)).ptr.storeInt(ptr11)
      }
      is io.github.glandais.engine.wit.Types.EngineError.Unsupported -> {
        val payload14 = x.value
        (ptr + 4).ptr.storeByte(3.toByte())

        val bytearray17 = payload14.encodeToByteArray()
        val len16 = bytearray17.size
        val ptr15 = allocator.writeToLinearMemory(bytearray17).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len16)
        (ptr + (2*4)).ptr.storeInt(ptr15)
      }
      else -> error("unreachable")
    }
    // VariantLower END
  } else {
    val payload = result.getOrThrow()!!
    (ptr + 0).ptr.storeByte(0.toByte())

    val bytearray = payload.encodeToByteArray()
    val len = bytearray.size
    val ptr3 = allocator.writeToLinearMemory(bytearray).address.toInt()

    (ptr + (2*4)).ptr.storeInt(len)
    (ptr + 4).ptr.storeInt(ptr3)
  }
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#[method]path.to-csv")
fun __wasm_export_toCsv(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int, p4: kotlin.Int, p5: kotlin.Int, p6: kotlin.Int, p7: kotlin.Int): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val resource = io.github.glandais.engine.wit.runtime.RepTable.get(p0) as PathApiImpl.PathImpl
  // OptionLift start
  val option2 = if (p1== 1) {
    // OptionLift start
    val option = if (p2== 1) {
      p3
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option0 = if (p4== 1) {
      (p5 != 0)
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option1 = if (p6== 1) {
      p7.toUByte()
    } else {
      null
    }
    // OptionLift end
    io.github.glandais.engine.wit.Types.CsvOptions(
    option,
    option0,
    option1,
    )
  } else {
    null
  }
  // OptionLift end
  val result: kotlin.Result<kotlin.String> = resource.toCsv(option2)

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(4*4), align=4)*/ allocator.allocate((4*4)).address.toInt()
  if (result.isFailure) {
    val payload4 = (result.exceptionOrNull() as io.github.glandais.engine.wit.runtime.ComponentException).value as io.github.glandais.engine.wit.Types.EngineError
    (ptr + 0).ptr.storeByte(1.toByte())
    // VariantLower START
    when (val x = payload4) {
      is io.github.glandais.engine.wit.Types.EngineError.Failed -> {
        val payload5 = x.value
        (ptr + 4).ptr.storeByte(0.toByte())

        val bytearray8 = payload5.encodeToByteArray()
        val len7 = bytearray8.size
        val ptr6 = allocator.writeToLinearMemory(bytearray8).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len7)
        (ptr + (2*4)).ptr.storeInt(ptr6)
      }
      is io.github.glandais.engine.wit.Types.EngineError.UnknownHandle -> {
        (ptr + 4).ptr.storeByte(1.toByte())
      }
      is io.github.glandais.engine.wit.Types.EngineError.InvalidArgument -> {
        val payload10 = x.value
        (ptr + 4).ptr.storeByte(2.toByte())

        val bytearray13 = payload10.encodeToByteArray()
        val len12 = bytearray13.size
        val ptr11 = allocator.writeToLinearMemory(bytearray13).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len12)
        (ptr + (2*4)).ptr.storeInt(ptr11)
      }
      is io.github.glandais.engine.wit.Types.EngineError.Unsupported -> {
        val payload14 = x.value
        (ptr + 4).ptr.storeByte(3.toByte())

        val bytearray17 = payload14.encodeToByteArray()
        val len16 = bytearray17.size
        val ptr15 = allocator.writeToLinearMemory(bytearray17).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len16)
        (ptr + (2*4)).ptr.storeInt(ptr15)
      }
      else -> error("unreachable")
    }
    // VariantLower END
  } else {
    val payload = result.getOrThrow()!!
    (ptr + 0).ptr.storeByte(0.toByte())

    val bytearray = payload.encodeToByteArray()
    val len = bytearray.size
    val ptr3 = allocator.writeToLinearMemory(bytearray).address.toInt()

    (ptr + (2*4)).ptr.storeInt(len)
    (ptr + 4).ptr.storeInt(ptr3)
  }
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#[method]path.to-json")
fun __wasm_export_toJson(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int, p4: kotlin.Int, p5: kotlin.Int, p6: kotlin.Int, p7: kotlin.Int): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val resource = io.github.glandais.engine.wit.runtime.RepTable.get(p0) as PathApiImpl.PathImpl
  // OptionLift start
  val option2 = if (p1== 1) {
    // OptionLift start
    val option = if (p2== 1) {
      (p3 != 0)
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option0 = if (p4== 1) {
      p5.toUByte()
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option1 = if (p6== 1) {
      (p7 != 0)
    } else {
      null
    }
    // OptionLift end
    io.github.glandais.engine.wit.Types.JsonOptions(
    option,
    option0,
    option1,
    )
  } else {
    null
  }
  // OptionLift end
  val result: kotlin.Result<kotlin.String> = resource.toJson(option2)

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(4*4), align=4)*/ allocator.allocate((4*4)).address.toInt()
  if (result.isFailure) {
    val payload4 = (result.exceptionOrNull() as io.github.glandais.engine.wit.runtime.ComponentException).value as io.github.glandais.engine.wit.Types.EngineError
    (ptr + 0).ptr.storeByte(1.toByte())
    // VariantLower START
    when (val x = payload4) {
      is io.github.glandais.engine.wit.Types.EngineError.Failed -> {
        val payload5 = x.value
        (ptr + 4).ptr.storeByte(0.toByte())

        val bytearray8 = payload5.encodeToByteArray()
        val len7 = bytearray8.size
        val ptr6 = allocator.writeToLinearMemory(bytearray8).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len7)
        (ptr + (2*4)).ptr.storeInt(ptr6)
      }
      is io.github.glandais.engine.wit.Types.EngineError.UnknownHandle -> {
        (ptr + 4).ptr.storeByte(1.toByte())
      }
      is io.github.glandais.engine.wit.Types.EngineError.InvalidArgument -> {
        val payload10 = x.value
        (ptr + 4).ptr.storeByte(2.toByte())

        val bytearray13 = payload10.encodeToByteArray()
        val len12 = bytearray13.size
        val ptr11 = allocator.writeToLinearMemory(bytearray13).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len12)
        (ptr + (2*4)).ptr.storeInt(ptr11)
      }
      is io.github.glandais.engine.wit.Types.EngineError.Unsupported -> {
        val payload14 = x.value
        (ptr + 4).ptr.storeByte(3.toByte())

        val bytearray17 = payload14.encodeToByteArray()
        val len16 = bytearray17.size
        val ptr15 = allocator.writeToLinearMemory(bytearray17).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len16)
        (ptr + (2*4)).ptr.storeInt(ptr15)
      }
      else -> error("unreachable")
    }
    // VariantLower END
  } else {
    val payload = result.getOrThrow()!!
    (ptr + 0).ptr.storeByte(0.toByte())

    val bytearray = payload.encodeToByteArray()
    val len = bytearray.size
    val ptr3 = allocator.writeToLinearMemory(bytearray).address.toInt()

    (ptr + (2*4)).ptr.storeInt(len)
    (ptr + 4).ptr.storeInt(ptr3)
  }
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#[method]path.to-fit")
fun __wasm_export_toFit(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int, p4: kotlin.Long, p5: kotlin.Int, p6: kotlin.Long): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val resource = io.github.glandais.engine.wit.runtime.RepTable.get(p0) as PathApiImpl.PathImpl
  // OptionLift start
  val option = if (p1== 1) {
    io.github.glandais.engine.wit.runtime.STRING_FROM_MEM(p2, p3)
  } else {
    null
  }
  // OptionLift end
  // OptionLift start
  val option0 = if (p5== 1) {
    p6
  } else {
    null
  }
  // OptionLift end
  val result: kotlin.Result<kotlin.collections.List<kotlin.UByte>> = resource.toFit(io.github.glandais.engine.wit.Types.FitOptions(
  option,
  p4,
  option0,
  ))

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(4*4), align=4)*/ allocator.allocate((4*4)).address.toInt()
  if (result.isFailure) {
    val payload1 = (result.exceptionOrNull() as io.github.glandais.engine.wit.runtime.ComponentException).value as io.github.glandais.engine.wit.Types.EngineError
    (ptr + 0).ptr.storeByte(1.toByte())
    // VariantLower START
    when (val x = payload1) {
      is io.github.glandais.engine.wit.Types.EngineError.Failed -> {
        val payload2 = x.value
        (ptr + 4).ptr.storeByte(0.toByte())

        val bytearray = payload2.encodeToByteArray()
        val len = bytearray.size
        val ptr3 = allocator.writeToLinearMemory(bytearray).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len)
        (ptr + (2*4)).ptr.storeInt(ptr3)
      }
      is io.github.glandais.engine.wit.Types.EngineError.UnknownHandle -> {
        (ptr + 4).ptr.storeByte(1.toByte())
      }
      is io.github.glandais.engine.wit.Types.EngineError.InvalidArgument -> {
        val payload5 = x.value
        (ptr + 4).ptr.storeByte(2.toByte())

        val bytearray8 = payload5.encodeToByteArray()
        val len7 = bytearray8.size
        val ptr6 = allocator.writeToLinearMemory(bytearray8).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len7)
        (ptr + (2*4)).ptr.storeInt(ptr6)
      }
      is io.github.glandais.engine.wit.Types.EngineError.Unsupported -> {
        val payload9 = x.value
        (ptr + 4).ptr.storeByte(3.toByte())

        val bytearray12 = payload9.encodeToByteArray()
        val len11 = bytearray12.size
        val ptr10 = allocator.writeToLinearMemory(bytearray12).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len11)
        (ptr + (2*4)).ptr.storeInt(ptr10)
      }
      else -> error("unreachable")
    }
    // VariantLower END
  } else {
    val payload = result.getOrThrow()!!
    (ptr + 0).ptr.storeByte(0.toByte())

    val address = allocator.allocate(payload.size * 1 /*, align_wasm32=1*/).address.toInt()
    for (iter in payload.withIndex()) {
      val index = iter.index
      val el = iter.value
      val base = address + (index * 1)
      (base + 0).ptr.storeByte(el.toInt().toByte())

    }
    (ptr + (2*4)).ptr.storeInt(payload.size)
    (ptr + 4).ptr.storeInt(address)
  }
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#parse-gpx")
fun __wasm_export_parseGpx(p0: kotlin.Int, p1: kotlin.Int): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val result: kotlin.Result<PathApiImpl.PathImpl> = PathApiImpl.parseGpx(io.github.glandais.engine.wit.runtime.STRING_FROM_MEM(p0, p1))

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(4*4), align=4)*/ allocator.allocate((4*4)).address.toInt()
  if (result.isFailure) {
    val payload0 = (result.exceptionOrNull() as io.github.glandais.engine.wit.runtime.ComponentException).value as io.github.glandais.engine.wit.Types.EngineError
    (ptr + 0).ptr.storeByte(1.toByte())
    // VariantLower START
    when (val x = payload0) {
      is io.github.glandais.engine.wit.Types.EngineError.Failed -> {
        val payload1 = x.value
        (ptr + 4).ptr.storeByte(0.toByte())

        val bytearray = payload1.encodeToByteArray()
        val len = bytearray.size
        val ptr2 = allocator.writeToLinearMemory(bytearray).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len)
        (ptr + (2*4)).ptr.storeInt(ptr2)
      }
      is io.github.glandais.engine.wit.Types.EngineError.UnknownHandle -> {
        (ptr + 4).ptr.storeByte(1.toByte())
      }
      is io.github.glandais.engine.wit.Types.EngineError.InvalidArgument -> {
        val payload4 = x.value
        (ptr + 4).ptr.storeByte(2.toByte())

        val bytearray7 = payload4.encodeToByteArray()
        val len6 = bytearray7.size
        val ptr5 = allocator.writeToLinearMemory(bytearray7).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len6)
        (ptr + (2*4)).ptr.storeInt(ptr5)
      }
      is io.github.glandais.engine.wit.Types.EngineError.Unsupported -> {
        val payload8 = x.value
        (ptr + 4).ptr.storeByte(3.toByte())

        val bytearray11 = payload8.encodeToByteArray()
        val len10 = bytearray11.size
        val ptr9 = allocator.writeToLinearMemory(bytearray11).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len10)
        (ptr + (2*4)).ptr.storeInt(ptr9)
      }
      else -> error("unreachable")
    }
    // VariantLower END
  } else {
    val payload = result.getOrThrow()!!
    (ptr + 0).ptr.storeByte(0.toByte())
    var handle = payload.__handle.value;
    if (handle == io.github.glandais.engine.wit.runtime.ResourceHandle.DOES_NOT_OWN_REP) {
      var localRep = io.github.glandais.engine.wit.runtime.RepTable.add(payload);
      handle = __cm_resource_abi_export_PathApiImpl_Path_new(localRep);
    }

    payload.__handle = io.github.glandais.engine.wit.runtime.ResourceHandle(0);
    (ptr + 4).ptr.storeInt(handle)
  }
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#parse-gpx-multi")
fun __wasm_export_parseGpxMulti(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val result: kotlin.Result<kotlin.collections.List<PathApiImpl.PathImpl>> = PathApiImpl.parseGpxMulti(io.github.glandais.engine.wit.runtime.STRING_FROM_MEM(p0, p1), io.github.glandais.engine.wit.PathApi.ParseMode.values()[p2])

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(4*4), align=4)*/ allocator.allocate((4*4)).address.toInt()
  if (result.isFailure) {
    val payload0 = (result.exceptionOrNull() as io.github.glandais.engine.wit.runtime.ComponentException).value as io.github.glandais.engine.wit.Types.EngineError
    (ptr + 0).ptr.storeByte(1.toByte())
    // VariantLower START
    when (val x = payload0) {
      is io.github.glandais.engine.wit.Types.EngineError.Failed -> {
        val payload1 = x.value
        (ptr + 4).ptr.storeByte(0.toByte())

        val bytearray = payload1.encodeToByteArray()
        val len = bytearray.size
        val ptr2 = allocator.writeToLinearMemory(bytearray).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len)
        (ptr + (2*4)).ptr.storeInt(ptr2)
      }
      is io.github.glandais.engine.wit.Types.EngineError.UnknownHandle -> {
        (ptr + 4).ptr.storeByte(1.toByte())
      }
      is io.github.glandais.engine.wit.Types.EngineError.InvalidArgument -> {
        val payload4 = x.value
        (ptr + 4).ptr.storeByte(2.toByte())

        val bytearray7 = payload4.encodeToByteArray()
        val len6 = bytearray7.size
        val ptr5 = allocator.writeToLinearMemory(bytearray7).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len6)
        (ptr + (2*4)).ptr.storeInt(ptr5)
      }
      is io.github.glandais.engine.wit.Types.EngineError.Unsupported -> {
        val payload8 = x.value
        (ptr + 4).ptr.storeByte(3.toByte())

        val bytearray11 = payload8.encodeToByteArray()
        val len10 = bytearray11.size
        val ptr9 = allocator.writeToLinearMemory(bytearray11).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len10)
        (ptr + (2*4)).ptr.storeInt(ptr9)
      }
      else -> error("unreachable")
    }
    // VariantLower END
  } else {
    val payload = result.getOrThrow()!!
    (ptr + 0).ptr.storeByte(0.toByte())

    val address = allocator.allocate(payload.size * 4 /*, align_wasm32=4*/).address.toInt()
    for (iter in payload.withIndex()) {
      val index = iter.index
      val el = iter.value
      val base = address + (index * 4)
      var handle = el.__handle.value;
      if (handle == io.github.glandais.engine.wit.runtime.ResourceHandle.DOES_NOT_OWN_REP) {
        var localRep = io.github.glandais.engine.wit.runtime.RepTable.add(el);
        handle = __cm_resource_abi_export_PathApiImpl_Path_new(localRep);
      }

      el.__handle = io.github.glandais.engine.wit.runtime.ResourceHandle(0);
      (base + 0).ptr.storeInt(handle)

    }
    (ptr + (2*4)).ptr.storeInt(payload.size)
    (ptr + 4).ptr.storeInt(address)
  }
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#parse-gpx-waypoints")
fun __wasm_export_parseGpxWaypoints(p0: kotlin.Int, p1: kotlin.Int): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val result: kotlin.Result<kotlin.collections.List<io.github.glandais.engine.wit.Types.Waypoint>> = PathApiImpl.parseGpxWaypoints(io.github.glandais.engine.wit.runtime.STRING_FROM_MEM(p0, p1))

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(4*4), align=4)*/ allocator.allocate((4*4)).address.toInt()
  if (result.isFailure) {
    val payload27 = (result.exceptionOrNull() as io.github.glandais.engine.wit.runtime.ComponentException).value as io.github.glandais.engine.wit.Types.EngineError
    (ptr + 0).ptr.storeByte(1.toByte())
    // VariantLower START
    when (val x = payload27) {
      is io.github.glandais.engine.wit.Types.EngineError.Failed -> {
        val payload28 = x.value
        (ptr + 4).ptr.storeByte(0.toByte())

        val bytearray31 = payload28.encodeToByteArray()
        val len30 = bytearray31.size
        val ptr29 = allocator.writeToLinearMemory(bytearray31).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len30)
        (ptr + (2*4)).ptr.storeInt(ptr29)
      }
      is io.github.glandais.engine.wit.Types.EngineError.UnknownHandle -> {
        (ptr + 4).ptr.storeByte(1.toByte())
      }
      is io.github.glandais.engine.wit.Types.EngineError.InvalidArgument -> {
        val payload33 = x.value
        (ptr + 4).ptr.storeByte(2.toByte())

        val bytearray36 = payload33.encodeToByteArray()
        val len35 = bytearray36.size
        val ptr34 = allocator.writeToLinearMemory(bytearray36).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len35)
        (ptr + (2*4)).ptr.storeInt(ptr34)
      }
      is io.github.glandais.engine.wit.Types.EngineError.Unsupported -> {
        val payload37 = x.value
        (ptr + 4).ptr.storeByte(3.toByte())

        val bytearray40 = payload37.encodeToByteArray()
        val len39 = bytearray40.size
        val ptr38 = allocator.writeToLinearMemory(bytearray40).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len39)
        (ptr + (2*4)).ptr.storeInt(ptr38)
      }
      else -> error("unreachable")
    }
    // VariantLower END
  } else {
    val payload = result.getOrThrow()!!
    (ptr + 0).ptr.storeByte(0.toByte())

    val address = allocator.allocate(payload.size * (48+12*4) /*, align_wasm32=8*/).address.toInt()
    for (iter in payload.withIndex()) {
      val index = iter.index
      val el = iter.value
      val base = address + (index * (48+12*4))
      (base + 0).ptr.storeDouble(el.latitudeDeg)
      (base + 8).ptr.storeDouble(el.longitudeDeg)
      val payload1 = el.elevationM
      if (payload1 != null) {
        (base + 16).ptr.storeByte(1.toByte())
        (base + 24).ptr.storeDouble(payload1)
      } else {
        (base + 16).ptr.storeByte(0.toByte())
      }
      val payload3 = el.name
      if (payload3 != null) {
        (base + 32).ptr.storeByte(1.toByte())

        val bytearray = payload3.encodeToByteArray()
        val len = bytearray.size
        val ptr4 = allocator.writeToLinearMemory(bytearray).address.toInt()

        (base + (32+2*4)).ptr.storeInt(len)
        (base + (32+1*4)).ptr.storeInt(ptr4)
      } else {
        (base + 32).ptr.storeByte(0.toByte())
      }
      val payload7 = el.description
      if (payload7 != null) {
        (base + (32+3*4)).ptr.storeByte(1.toByte())

        val bytearray10 = payload7.encodeToByteArray()
        val len9 = bytearray10.size
        val ptr8 = allocator.writeToLinearMemory(bytearray10).address.toInt()

        (base + (32+5*4)).ptr.storeInt(len9)
        (base + (32+4*4)).ptr.storeInt(ptr8)
      } else {
        (base + (32+3*4)).ptr.storeByte(0.toByte())
      }
      val payload13 = el.symbol
      if (payload13 != null) {
        (base + (32+6*4)).ptr.storeByte(1.toByte())

        val bytearray16 = payload13.encodeToByteArray()
        val len15 = bytearray16.size
        val ptr14 = allocator.writeToLinearMemory(bytearray16).address.toInt()

        (base + (32+8*4)).ptr.storeInt(len15)
        (base + (32+7*4)).ptr.storeInt(ptr14)
      } else {
        (base + (32+6*4)).ptr.storeByte(0.toByte())
      }
      val payload19 = el.type
      if (payload19 != null) {
        (base + (32+9*4)).ptr.storeByte(1.toByte())

        val bytearray22 = payload19.encodeToByteArray()
        val len21 = bytearray22.size
        val ptr20 = allocator.writeToLinearMemory(bytearray22).address.toInt()

        (base + (32+11*4)).ptr.storeInt(len21)
        (base + (32+10*4)).ptr.storeInt(ptr20)
      } else {
        (base + (32+9*4)).ptr.storeByte(0.toByte())
      }
      val payload25 = el.timeEpochMs
      if (payload25 != null) {
        (base + (32+12*4)).ptr.storeByte(1.toByte())
        (base + (40+12*4)).ptr.storeDouble(payload25)
      } else {
        (base + (32+12*4)).ptr.storeByte(0.toByte())
      }

    }
    (ptr + (2*4)).ptr.storeInt(payload.size)
    (ptr + 4).ptr.storeInt(address)
  }
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#field-definitions")
fun __wasm_export_fieldDefinitions(): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val result: kotlin.collections.List<io.github.glandais.engine.wit.Types.FieldDefinition> = PathApiImpl.fieldDefinitions()

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(2*4), align=4)*/ allocator.allocate((2*4)).address.toInt()

  val address = allocator.allocate(result.size * (11*4) /*, align_wasm32=4*/).address.toInt()
  for (iter in result.withIndex()) {
    val index = iter.index
    val el = iter.value
    val base = address + (index * (11*4))
    
    val bytearray = el.prop.encodeToByteArray()
    val len = bytearray.size
    val ptr0 = allocator.writeToLinearMemory(bytearray).address.toInt()

    (base + 4).ptr.storeInt(len)
    (base + 0).ptr.storeInt(ptr0)

    val bytearray3 = el.unit.encodeToByteArray()
    val len2 = bytearray3.size
    val ptr1 = allocator.writeToLinearMemory(bytearray3).address.toInt()

    (base + (3*4)).ptr.storeInt(len2)
    (base + (2*4)).ptr.storeInt(ptr1)

    val bytearray6 = el.shortDescription.encodeToByteArray()
    val len5 = bytearray6.size
    val ptr4 = allocator.writeToLinearMemory(bytearray6).address.toInt()

    (base + (5*4)).ptr.storeInt(len5)
    (base + (4*4)).ptr.storeInt(ptr4)

    val bytearray9 = el.categoryId.encodeToByteArray()
    val len8 = bytearray9.size
    val ptr7 = allocator.writeToLinearMemory(bytearray9).address.toInt()

    (base + (7*4)).ptr.storeInt(len8)
    (base + (6*4)).ptr.storeInt(ptr7)

    val bytearray12 = el.categoryName.encodeToByteArray()
    val len11 = bytearray12.size
    val ptr10 = allocator.writeToLinearMemory(bytearray12).address.toInt()

    (base + (9*4)).ptr.storeInt(len11)
    (base + (8*4)).ptr.storeInt(ptr10)
    (base + (10*4)).ptr.storeByte((if(el.notSelectable) 1 else 0).toByte())
    (base + (1+10*4)).ptr.storeByte((if(el.anglesInRadians) 1 else 0).toByte())

  }
  (ptr + 4).ptr.storeInt(result.size)
  (ptr + 0).ptr.storeInt(address)
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#write-gpx-tracks")
fun __wasm_export_writeGpxTracks(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int, p4: kotlin.Int, p5: kotlin.Int, p6: kotlin.Int, p7: kotlin.Int, p8: kotlin.Int, p9: kotlin.Long): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->

  val list = kotlin.collections.ArrayList<PathApiImpl.PathImpl>(p1)
  for (i in 0 until p1) {
    val base = (p0) + (i * 4)
    val resource = io.github.glandais.engine.wit.runtime.RepTable.get((base + 0).ptr.loadInt()) as PathApiImpl.PathImpl

    list.add(resource)
  }
  // OptionLift start
  val option2 = if (p2== 1) {
    // OptionLift start
    val option = if (p3== 1) {
      (p4 != 0)
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option0 = if (p5== 1) {
      io.github.glandais.engine.wit.runtime.STRING_FROM_MEM(p6, p7)
    } else {
      null
    }
    // OptionLift end
    // OptionLift start
    val option1 = if (p8== 1) {
      p9
    } else {
      null
    }
    // OptionLift end
    io.github.glandais.engine.wit.Types.GpxWriteOptions(
    option,
    option0,
    option1,
    )
  } else {
    null
  }
  // OptionLift end
  val result: kotlin.Result<kotlin.String> = PathApiImpl.writeGpxTracks(list, option2)

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(4*4), align=4)*/ allocator.allocate((4*4)).address.toInt()
  if (result.isFailure) {
    val payload4 = (result.exceptionOrNull() as io.github.glandais.engine.wit.runtime.ComponentException).value as io.github.glandais.engine.wit.Types.EngineError
    (ptr + 0).ptr.storeByte(1.toByte())
    // VariantLower START
    when (val x = payload4) {
      is io.github.glandais.engine.wit.Types.EngineError.Failed -> {
        val payload5 = x.value
        (ptr + 4).ptr.storeByte(0.toByte())

        val bytearray8 = payload5.encodeToByteArray()
        val len7 = bytearray8.size
        val ptr6 = allocator.writeToLinearMemory(bytearray8).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len7)
        (ptr + (2*4)).ptr.storeInt(ptr6)
      }
      is io.github.glandais.engine.wit.Types.EngineError.UnknownHandle -> {
        (ptr + 4).ptr.storeByte(1.toByte())
      }
      is io.github.glandais.engine.wit.Types.EngineError.InvalidArgument -> {
        val payload10 = x.value
        (ptr + 4).ptr.storeByte(2.toByte())

        val bytearray13 = payload10.encodeToByteArray()
        val len12 = bytearray13.size
        val ptr11 = allocator.writeToLinearMemory(bytearray13).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len12)
        (ptr + (2*4)).ptr.storeInt(ptr11)
      }
      is io.github.glandais.engine.wit.Types.EngineError.Unsupported -> {
        val payload14 = x.value
        (ptr + 4).ptr.storeByte(3.toByte())

        val bytearray17 = payload14.encodeToByteArray()
        val len16 = bytearray17.size
        val ptr15 = allocator.writeToLinearMemory(bytearray17).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len16)
        (ptr + (2*4)).ptr.storeInt(ptr15)
      }
      else -> error("unreachable")
    }
    // VariantLower END
  } else {
    val payload = result.getOrThrow()!!
    (ptr + 0).ptr.storeByte(0.toByte())

    val bytearray = payload.encodeToByteArray()
    val len = bytearray.size
    val ptr3 = allocator.writeToLinearMemory(bytearray).address.toInt()

    (ptr + (2*4)).ptr.storeInt(len)
    (ptr + 4).ptr.storeInt(ptr3)
  }
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#paths-to-fit")
fun __wasm_export_pathsToFit(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int, p4: kotlin.Int, p5: kotlin.Long, p6: kotlin.Int, p7: kotlin.Long): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->

  val list = kotlin.collections.ArrayList<PathApiImpl.PathImpl>(p1)
  for (i in 0 until p1) {
    val base = (p0) + (i * 4)
    val resource = io.github.glandais.engine.wit.runtime.RepTable.get((base + 0).ptr.loadInt()) as PathApiImpl.PathImpl

    list.add(resource)
  }
  // OptionLift start
  val option = if (p2== 1) {
    io.github.glandais.engine.wit.runtime.STRING_FROM_MEM(p3, p4)
  } else {
    null
  }
  // OptionLift end
  // OptionLift start
  val option0 = if (p6== 1) {
    p7
  } else {
    null
  }
  // OptionLift end
  val result: kotlin.Result<kotlin.collections.List<kotlin.UByte>> = PathApiImpl.pathsToFit(list, io.github.glandais.engine.wit.Types.FitOptions(
  option,
  p5,
  option0,
  ))

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(4*4), align=4)*/ allocator.allocate((4*4)).address.toInt()
  if (result.isFailure) {
    val payload1 = (result.exceptionOrNull() as io.github.glandais.engine.wit.runtime.ComponentException).value as io.github.glandais.engine.wit.Types.EngineError
    (ptr + 0).ptr.storeByte(1.toByte())
    // VariantLower START
    when (val x = payload1) {
      is io.github.glandais.engine.wit.Types.EngineError.Failed -> {
        val payload2 = x.value
        (ptr + 4).ptr.storeByte(0.toByte())

        val bytearray = payload2.encodeToByteArray()
        val len = bytearray.size
        val ptr3 = allocator.writeToLinearMemory(bytearray).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len)
        (ptr + (2*4)).ptr.storeInt(ptr3)
      }
      is io.github.glandais.engine.wit.Types.EngineError.UnknownHandle -> {
        (ptr + 4).ptr.storeByte(1.toByte())
      }
      is io.github.glandais.engine.wit.Types.EngineError.InvalidArgument -> {
        val payload5 = x.value
        (ptr + 4).ptr.storeByte(2.toByte())

        val bytearray8 = payload5.encodeToByteArray()
        val len7 = bytearray8.size
        val ptr6 = allocator.writeToLinearMemory(bytearray8).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len7)
        (ptr + (2*4)).ptr.storeInt(ptr6)
      }
      is io.github.glandais.engine.wit.Types.EngineError.Unsupported -> {
        val payload9 = x.value
        (ptr + 4).ptr.storeByte(3.toByte())

        val bytearray12 = payload9.encodeToByteArray()
        val len11 = bytearray12.size
        val ptr10 = allocator.writeToLinearMemory(bytearray12).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len11)
        (ptr + (2*4)).ptr.storeInt(ptr10)
      }
      else -> error("unreachable")
    }
    // VariantLower END
  } else {
    val payload = result.getOrThrow()!!
    (ptr + 0).ptr.storeByte(0.toByte())

    val address = allocator.allocate(payload.size * 1 /*, align_wasm32=1*/).address.toInt()
    for (iter in payload.withIndex()) {
      val index = iter.index
      val el = iter.value
      val base = address + (index * 1)
      (base + 0).ptr.storeByte(el.toInt().toByte())

    }
    (ptr + (2*4)).ptr.storeInt(payload.size)
    (ptr + 4).ptr.storeInt(address)
  }
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/path-api@1.0.0#dominant-headwind-azimuth-of-tracks")
fun __wasm_export_dominantHeadwindAzimuthOfTracks(p0: kotlin.Int, p1: kotlin.Int): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->

  val list = kotlin.collections.ArrayList<PathApiImpl.PathImpl>(p1)
  for (i in 0 until p1) {
    val base = (p0) + (i * 4)
    val resource = io.github.glandais.engine.wit.runtime.RepTable.get((base + 0).ptr.loadInt()) as PathApiImpl.PathImpl

    list.add(resource)
  }
  val result: kotlin.Double? = PathApiImpl.dominantHeadwindAzimuthOfTracks(list)

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=16, align=8)*/ allocator.allocate(16).address.toInt()
  val payload0 = result
  if (payload0 != null) {
    (ptr + 0).ptr.storeByte(1.toByte())
    (ptr + 8).ptr.storeDouble(payload0)
  } else {
    (ptr + 0).ptr.storeByte(0.toByte())
  }
  return ptr
}
}



@kotlin.wasm.WasmExport("vcyclist:engine/elevation@1.0.0#set-config")
fun __wasm_export_setConfig(p0: kotlin.Int, p1: kotlin.Int, p2: kotlin.Int, p3: kotlin.Int, p4: kotlin.Int, p5: kotlin.Int, p6: kotlin.Int, p7: kotlin.Int): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  // OptionLift start
  val option = if (p0== 1) {
    p1.toUInt()
  } else {
    null
  }
  // OptionLift end
  // OptionLift start
  val option0 = if (p2== 1) {
    p3.toUInt()
  } else {
    null
  }
  // OptionLift end
  // OptionLift start
  val option1 = if (p4== 1) {
    p5.toUInt()
  } else {
    null
  }
  // OptionLift end
  // OptionLift start
  val option2 = if (p6== 1) {
    io.github.glandais.engine.wit.Types.TileFormat.values()[p7]
  } else {
    null
  }
  // OptionLift end
  val result: kotlin.Result<kotlin.Unit> = ElevationImpl.setConfig(io.github.glandais.engine.wit.Types.ElevationConfig(
  option,
  option0,
  option1,
  option2,
  ))

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(4*4), align=4)*/ allocator.allocate((4*4)).address.toInt()
  if (result.isFailure) {
    val payload3 = (result.exceptionOrNull() as io.github.glandais.engine.wit.runtime.ComponentException).value as io.github.glandais.engine.wit.Types.EngineError
    (ptr + 0).ptr.storeByte(1.toByte())
    // VariantLower START
    when (val x = payload3) {
      is io.github.glandais.engine.wit.Types.EngineError.Failed -> {
        val payload4 = x.value
        (ptr + 4).ptr.storeByte(0.toByte())

        val bytearray = payload4.encodeToByteArray()
        val len = bytearray.size
        val ptr5 = allocator.writeToLinearMemory(bytearray).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len)
        (ptr + (2*4)).ptr.storeInt(ptr5)
      }
      is io.github.glandais.engine.wit.Types.EngineError.UnknownHandle -> {
        (ptr + 4).ptr.storeByte(1.toByte())
      }
      is io.github.glandais.engine.wit.Types.EngineError.InvalidArgument -> {
        val payload7 = x.value
        (ptr + 4).ptr.storeByte(2.toByte())

        val bytearray10 = payload7.encodeToByteArray()
        val len9 = bytearray10.size
        val ptr8 = allocator.writeToLinearMemory(bytearray10).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len9)
        (ptr + (2*4)).ptr.storeInt(ptr8)
      }
      is io.github.glandais.engine.wit.Types.EngineError.Unsupported -> {
        val payload11 = x.value
        (ptr + 4).ptr.storeByte(3.toByte())

        val bytearray14 = payload11.encodeToByteArray()
        val len13 = bytearray14.size
        val ptr12 = allocator.writeToLinearMemory(bytearray14).address.toInt()

        (ptr + (3*4)).ptr.storeInt(len13)
        (ptr + (2*4)).ptr.storeInt(ptr12)
      }
      else -> error("unreachable")
    }
    // VariantLower END
  } else {
    (ptr + 0).ptr.storeByte(0.toByte())
  }
  return ptr
}
}

@kotlin.wasm.WasmExport("vcyclist:engine/elevation@1.0.0#geometry")
fun __wasm_export_geometry(): kotlin.Int {
  kotlin.wasm.unsafe.freeAllComponentModelReallocAllocatedMemory()
  kotlin.wasm.unsafe.withScopedMemoryAllocator { allocator ->
  val result: io.github.glandais.engine.wit.Types.TileGeometry = ElevationImpl.geometry()

  val ptr = /* RETURN_ADDRESS_ALLOC(size_wasm32=(16+5*4), align=4)*/ allocator.allocate((16+5*4)).address.toInt()
  (ptr + 0).ptr.storeInt(result.tileSize.toInt())
  (ptr + 4).ptr.storeInt(result.bytesPerPixel.toInt())
  (ptr + 8).ptr.storeInt(result.expectedBytes.toInt())

  val bytearray = result.layout.encodeToByteArray()
  val len = bytearray.size
  val ptr0 = allocator.writeToLinearMemory(bytearray).address.toInt()

  (ptr + (8+2*4)).ptr.storeInt(len)
  (ptr + (8+1*4)).ptr.storeInt(ptr0)

  val bytearray3 = result.encoding.encodeToByteArray()
  val len2 = bytearray3.size
  val ptr1 = allocator.writeToLinearMemory(bytearray3).address.toInt()

  (ptr + (8+4*4)).ptr.storeInt(len2)
  (ptr + (8+3*4)).ptr.storeInt(ptr1)
  (ptr + (8+5*4)).ptr.storeInt(result.zoomLevel.toInt())
  (ptr + (12+5*4)).ptr.storeByte(result.tileFormat.ordinal.toByte())
  return ptr
}
}


