package io.github.glandais.engine.parity

/**
 * Reference metrics for `Enhancer.enhanceCourseDefault` outputs. Used by
 * [EnhancerParityTest] as a regression baseline.
 *
 * ## Source
 *
 * **Self-referential** : these values are *measured* from the Kotlin pipeline itself,
 * not generated by the TS reference (`virtual-cyclist`). The TS reference would require
 * a Node + npm build pipeline that is non-trivial to invoke from this Kotlin repo, and
 * even if available the two implementations cannot bit-match (atan2/sin/cos/sqrt ULP
 * differences, `PointPerDistance` not yet ported, etc.). Self-referential parity catches
 * **regressions** in the Kotlin pipeline ; documented in `docs/parity.md`.
 *
 * ## Pipeline used
 *
 * ```
 * val path = GpxParser.parse(GpxFixtures.<FIXTURE>).firstTrackAsPath()
 * Enhancer.enhanceCourseDefault(
 *     path,
 *     elevationProvider = null,
 *     options = EnhanceOptions.DEFAULT.copy(fixElevation = false),
 * )
 * ```
 *
 * ## When to update
 *
 * If you intentionally change the physics or the resampling/simplification defaults,
 * re-run [EnhancerParityTest.printMeasured] (temporary diagnostics method) on a clean
 * build and copy the new values here. Add a comment explaining the deviation.
 *
 * **Measured at task 26 commit (Kotlin pipeline, JVM target, May 2026).** Cross-target
 * stability is within 0.5 % per [EnhancerParityTest] tolerances.
 *
 * **Refreshed at task 29 (May 2026)** : durations dropped (SAMPLE 89 000 → 52 000 ms ;
 * GARMIN 18 000 → 5 000 ms) because `VirtualizeService` no longer leaves `time(n - 1)`
 * at the raw source epoch — the last point is fully simulated now, so the reported
 * duration reflects only the simulated ride time instead of `simulated + epoch offset`.
 *
 * **Refreshed at task 31 (May 2026, Phase 2bis)** : `PointPerDistance` is now wired into
 * `Enhancer` (pre-fix densify at 30 m max, post-fix refine at 1-2 m). On the short fixtures
 * this densifies the 7-trkpt `SAMPLE_GPX` (~70 m mean gap → ~210 segments of ~2 m) before
 * physics. Distance/gain/loss/duration shift slightly (denser MaxSpeedComputer + Virtualize
 * grid), but Douglas-Peucker still collapses to 3 (SAMPLE) / 2 (GARMIN) points. SAMPLE
 * durationMs : 52 000 → 49 000 ms ; SAMPLE gain : 0.268 → 0.219 m ; GARMIN loss : -0.0086
 * → -0.0048 m.
 */
data class ParityMetrics(
    val totalDistance: Double,
    val totalElevationGain: Double,
    val totalElevationLoss: Double,
    val pointCount: Int,
    val durationMs: Double,
)

object ParityFixtures {
    /**
     * Measured for `GpxFixtures.SAMPLE_GPX` (étape du Tour 2025 excerpt, 7 trkpts spanning
     * ~89 s of riding). Output is simplified down to 3 points by Douglas-Peucker.
     *
     * Measured Kotlin pipeline at task 26 commit.
     */
    val SAMPLE =
        ParityMetrics(
            // updated for Phase 2bis (task 31): PointPerDistance integrated.
            totalDistance = 420.04525064910683,
            totalElevationGain = 0.2189461508746149,
            totalElevationLoss = -0.3083313825632672,
            pointCount = 3,
            durationMs = 49_000.0,
        )

    /**
     * Measured for `GpxFixtures.GARMIN_GPX` (3 trkpts, Garmin-style extensions, ~18 s span).
     * Trivially short ride : output collapses to 2 points (start + end) after simplify.
     *
     * Measured Kotlin pipeline at task 26 commit.
     */
    val GARMIN =
        ParityMetrics(
            // updated for Phase 2bis (task 31): PointPerDistance integrated.
            totalDistance = 14.929920010888091,
            totalElevationGain = 0.0,
            totalElevationLoss = -0.004834919456122577,
            pointCount = 2,
            durationMs = 5_000.0,
        )
}
