package io.github.glandais.engine.parity

/**
 * Reference metrics for `Enhancer.enhanceCourseDefault` outputs. Used by
 * [EnhancerParityTest] as a regression baseline.
 *
 * ## Source
 *
 * **Self-referential** : these values are *measured* from the Kotlin pipeline itself,
 * not generated by the TS reference (`virtual-cyclist`). The TS reference would require
 * a Node + npm build pipeline that is non-trivial to invoke from this Kotlin repo, and
 * even if available the two implementations cannot bit-match (atan2/sin/cos/sqrt ULP
 * differences, `PointPerDistance` not yet ported, etc.). Self-referential parity catches
 * **regressions** in the Kotlin pipeline ; documented in `docs/parity.md`.
 *
 * ## Pipeline used
 *
 * ```
 * val path = GpxParser.parse(GpxFixtures.<FIXTURE>).firstTrackAsPath()
 * Enhancer.enhanceCourseDefault(
 *     path,
 *     elevationProvider = null,
 *     options = EnhanceOptions.DEFAULT.copy(fixElevation = false),
 * )
 * ```
 *
 * ## When to update
 *
 * If you intentionally change the physics or the resampling/simplification defaults,
 * re-run [EnhancerParityTest.printMeasured] (temporary diagnostics method) on a clean
 * build and copy the new values here. Add a comment explaining the deviation.
 *
 * **Measured at task 26 commit (Kotlin pipeline, JVM target, May 2026).** Cross-target
 * stability is within 0.5 % per [EnhancerParityTest] tolerances.
 */
data class ParityMetrics(
    val totalDistance: Double,
    val totalElevationGain: Double,
    val totalElevationLoss: Double,
    val pointCount: Int,
    val durationMs: Double,
)

object ParityFixtures {
    /**
     * Measured for `GpxFixtures.SAMPLE_GPX` (étape du Tour 2025 excerpt, 7 trkpts spanning
     * ~89 s of riding). Output is simplified down to 3 points by Douglas-Peucker.
     *
     * Measured Kotlin pipeline at task 26 commit.
     */
    val SAMPLE =
        ParityMetrics(
            totalDistance = 420.05059877583545,
            totalElevationGain = 0.26831277485973715,
            totalElevationLoss = -0.30660234137462794,
            pointCount = 3,
            durationMs = 89_000.0,
        )

    /**
     * Measured for `GpxFixtures.GARMIN_GPX` (3 trkpts, Garmin-style extensions, ~18 s span).
     * Trivially short ride : output collapses to 2 points (start + end) after simplify.
     *
     * Measured Kotlin pipeline at task 26 commit.
     */
    val GARMIN =
        ParityMetrics(
            totalDistance = 14.929920010888091,
            totalElevationGain = 0.0,
            totalElevationLoss = -0.008580953441633454,
            pointCount = 2,
            durationMs = 18_000.0,
        )
}
